In [1]:
import os
import time
import openai
import pickle
import tiktoken as tiktoken
from openai import OpenAI
import pandas as pd
import ast

In [2]:
api_key = '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'
# GPT_MODEL = 'gpt-4o-mini'
max_num_tokens_gpt4 = 128000
GPT_MODEL = 'o1-mini'

# Initialize the OpenAI client
client = OpenAI(api_key=api_key)

def BasicGeneration(userPrompt):
    completion = client.chat.completions.create(
        model = GPT_MODEL,
        messages=[

            {"role": "user", "content": userPrompt}
        ]
    )
    return completion.choices[0].message.content

# def RoleGeneration(userPrompt):
#     completion = client.chat.completions.create(
#         model = GPT_MODEL,
#         messages=[
#             {"role": "system", "content": "You are a expert in asset and construction management domain."},
#             {"role": "user", "content": userPrompt}
#         ]
#     )
#     return completion.choices[0].message.content

def RoleGeneration(userPrompt):
    full_prompt = "You are an expert in asset and construction management domain. " + userPrompt
    completion = client.chat.completions.create(
        model=GPT_MODEL,
        messages=[
            {"role": "user", "content": full_prompt}
        ]
    )
    return completion.choices[0].message.content

# Add topics into excel sheet

In [3]:
import pandas as pd
import re
from pathlib import Path

# Define paths (update these as needed)
excel_path = Path("../../tcm/collected_dataset/additional_data/data_collection_additional.xlsx")        # Path to your Excel file
txt_folder = Path('../../tcm/collected_dataset/additional_data/summarized_topics/')   # Path to the folder containing .txt files

# Load the Excel sheet into a DataFrame
df = pd.read_excel(excel_path)
df

,Index,File_Name,Paper_Name,Keywords,Topics,Journal_Name,Published_Year,Country,Continent,URL,...,lda_topics,broad_topics,jaccard_similarity_lda,jaccard_similarity_llm,BLEU_LDA,BLEU_LLM,ROUGE3_LDA,ROUGE2_LDA,ROUGE3_LLM,ROUGE2_LLM
0,748,748.pdf,Innovative BIM technology application in the c...,['Building Information Modeling; Highway; Cons...,NaN,Scientific Reports,2024,China,Asia,https://www.nature.com/articles/s41598-024-662...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,749,749.pdf,Domain-specific language models pre-trained on...,['Construction management; Domain-specific lar...,NaN,Automation in Construction,2024,Canada,North America,https://www.sciencedirect.com/science/article/...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,750,750.pdf,Integrating Artificial Intelligence in Constru...,['Artificial Intelligence; Construction Manage...,NaN,International Journal of Advanced Multidiscipl...,2024,Nigeria,Africa,https://www.multiresearchjournal.com/admin/upl...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,751,751.pdf,Digital twin-enabled synchronized construction...,['Digital twin; Construction management; Const...,NaN,Research and Studies,2024,China,Asia,https://www.sciencedirect.com/science/article/...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,752,752.pdf,Ecosystems in construction management and urba...,['Literature review; Business ecosystem; Innov...,NaN,Construction Management and Economics,2024,Sweden,Europe,https://www.tandfonline.com/doi/full/10.1080/0...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349,1013,1013.pdf,Japan's building industry: The new model,['Japan; building industry; change; model buil...,NaN,Construction Management and Economics,1993,United Kingdom,Europe,https://www.tandfonline.com/doi/abs/10.1080/01...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,1014,1014.pdf,Forecasting methodology of national demand for...,['Building economics; forecasting; label stati...,NaN,Construction Management and Economics,1993,United States,North America,https://www.tandfonline.com/doi/abs/10.1080/01...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
351,1015,1015.pdf,Estimating industry-level productivity trends ...,['Total factor productivity; productivity; Hon...,NaN,Construction Management and Economics,1993,Hong Kong,Asia,https://www.tandfonline.com/doi/abs/10.1080/01...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
352,1016,1016.pdf,Masonry productivity forecasting model,NaN,NaN,Journal of construction engineering and manage...,1993,United States,North America,https://ascelibrary.org/doi/abs/10.1061/(ASCE)...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
353,1017,1017.pdf,Integrated construction project document manag...,['CIC; conceptual modelling; integration; docu...,NaN,Proceedings of EuropIA,1993,Findland,Europe,https://citeseerx.ist.psu.edu/document?repid=r...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Regular expression to extract the topics line
topic_pattern = re.compile(r"topics:\s*(.*?)\s*(?:Summary:|$)", re.IGNORECASE | re.DOTALL)

def extract_topics(text: str) -> str:
    """Extracts a list of topics from the text of a .txt file."""
    match = topic_pattern.search(text)
    if not match:
        return []
    topics_str = match.group(1)
    # Split on commas and strip whitespace
    return str([topic.strip() for topic in topics_str.split(",") if topic.strip()])

In [5]:
extract_topics('''
topics: Artificial intelligence integration, Construction project management, Predictive analytics, Machine learning algorithms, Resource optimization, Risk management, Real-time data processing, Safety enhancement, Cloud computing, Emerging technologies collaboration
''')

"['Artificial intelligence integration', 'Construction project management', 'Predictive analytics', 'Machine learning algorithms', 'Resource optimization', 'Risk management', 'Real-time data processing', 'Safety enhancement', 'Cloud computing', 'Emerging technologies collaboration']"

In [6]:
# Iterate over DataFrame rows and update the 'Topics' column
import chardet
for idx, row in df.iterrows():
    file_index = str(row["Index"])
    txt_path = txt_folder / f"{file_index}.txt"
    if txt_path.is_file():
        raw = Path(txt_path).read_bytes()
        detected = chardet.detect(raw)
        encoding = detected.get("encoding", "utf-8")
        content = raw.decode(encoding, errors="replace")
        df.at[idx, "Topics"] = extract_topics(content)
    else:
        df.at[idx, "Topics"] = []

# Display the first few rows to confirm
df

C:\Users\zhong\AppData\Local\Temp\ipykernel_18248\3742886271.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['BIM technology', 'Highway construction', 'GIS integration', 'IoT monitoring', 'Construction simulation', '4D scheduling', 'Clash detection', 'Project management platform', 'Digital twin', 'Virtual Reality safety']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[idx, "Topics"] = extract_topics(content)

,Index,File_Name,Paper_Name,Keywords,Topics,Journal_Name,Published_Year,Country,Continent,URL,...,lda_topics,broad_topics,jaccard_similarity_lda,jaccard_similarity_llm,BLEU_LDA,BLEU_LLM,ROUGE3_LDA,ROUGE2_LDA,ROUGE3_LLM,ROUGE2_LLM
0,748,748.pdf,Innovative BIM technology application in the c...,['Building Information Modeling; Highway; Cons...,"['BIM technology', 'Highway construction', 'GI...",Scientific Reports,2024,China,Asia,https://www.nature.com/articles/s41598-024-662...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,749,749.pdf,Domain-specific language models pre-trained on...,['Construction management; Domain-specific lar...,"['Construction management systems', 'Transform...",Automation in Construction,2024,Canada,North America,https://www.sciencedirect.com/science/article/...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,750,750.pdf,Integrating Artificial Intelligence in Constru...,['Artificial Intelligence; Construction Manage...,"['Artificial Intelligence integration', 'Const...",International Journal of Advanced Multidiscipl...,2024,Nigeria,Africa,https://www.multiresearchjournal.com/admin/upl...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,751,751.pdf,Digital twin-enabled synchronized construction...,['Digital twin; Construction management; Const...,"['Construction 4.0', 'Digital twin', 'Synchron...",Research and Studies,2024,China,Asia,https://www.sciencedirect.com/science/article/...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,752,752.pdf,Ecosystems in construction management and urba...,['Literature review; Business ecosystem; Innov...,"['Ecosystem conceptualizations', 'Construction...",Construction Management and Economics,2024,Sweden,Europe,https://www.tandfonline.com/doi/full/10.1080/0...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349,1013,1013.pdf,Japan's building industry: The new model,['Japan; building industry; change; model buil...,"['Japanese building industry', 'Big five contr...",Construction Management and Economics,1993,United Kingdom,Europe,https://www.tandfonline.com/doi/abs/10.1080/01...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,1014,1014.pdf,Forecasting methodology of national demand for...,['Building economics; forecasting; label stati...,"['Construction labour forecasting', 'National ...",Construction Management and Economics,1993,United States,North America,https://www.tandfonline.com/doi/abs/10.1080/01...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
351,1015,1015.pdf,Estimating industry-level productivity trends ...,['Total factor productivity; productivity; Hon...,"['Total-factor productivity', 'Building indust...",Construction Management and Economics,1993,Hong Kong,Asia,https://www.tandfonline.com/doi/abs/10.1080/01...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
352,1016,1016.pdf,Masonry productivity forecasting model,NaN,"['Masonry labor productivity', 'Productivity f...",Journal of construction engineering and manage...,1993,United States,North America,https://ascelibrary.org/doi/abs/10.1061/(ASCE)...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
353,1017,1017.pdf,Integrated construction project document manag...,['CIC; conceptual modelling; integration; docu...,"['Integrated document management', 'Computer i...",Proceedings of EuropIA,1993,Findland,Europe,https://citeseerx.ist.psu.edu/document?repid=r...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# Save the updated DataFrame back to Excel
df.to_excel("../../tcm/collected_dataset/additional_data/data_collection_additional_with_topics.xlsx", index=False)

# Preprocess the text files

In [3]:
# input_directory = '/Users/yunshunzhong/Library/Mobile Documents/3L68KQB4HG~com~readdle~CommonDocuments/Documents/PhD Project/Topics analysis/'
# output_directory = input_directory
# 
# # List to store filenames that exceed the max token count
# filenames_exceeding_max_tokens = []
# output_file_name = 'summarized_broader_topics_index_first_half'
# # Iterate through each file in the folder
# filename1 = 'all_topics_first_half'
# filename2 = 'all_topics_second_half'

In [4]:


# with open(os.path.join(input_directory, filename1), 'rb') as file:
#     # Read the file content
#     file_contents1 = pickle.load(file)
# 
# with open(os.path.join(input_directory, filename2), 'rb') as file:
#     # Read the file content
#     file_contents2 = pickle.load(file)
# 
# file_contents = file_contents1 + file_contents2

In [5]:
# len(file_contents)

3983

In [9]:
# type(file_contents)

list

In [14]:
folder_path = '../../tcm/topics_outputs/2after_lda/'
df = pd.read_excel(os.path.join(folder_path, 'topics_citation_full_dataset_with_additional_gl.xlsx'))
df

,Index,File_Name,Paper_Name,Keywords,Topics,Journal_Name,Published_Year,Country,Continent,URL,...,1987,1986,1985,1984,1983,1982,1981,1980,ground_truth_topics,lda_topics
0,0,(ASCE)0733-9364(1986)112_3(346).pdf,RESOURCE MANAGEMENT IN CONSTRUCTION,[],"['Resource management', 'Construction industry...",Journal of construction engineering and manage...,1986,United States,North America,https://scholar.google.com/scholar?hl=en&as_sd...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"['Resource planning', 'cost control', 'constru...","['analysis', 'earliest', 'resources', 'activit..."
1,2,(ASCE)0742-597X(2005)21_1(2).pdf,Competency-Based Model for Predicting Construc...,['Human factors; Professional development; Pro...,"['Construction project management', 'Competenc...",Journal of Management in Engineering,2005,United Kingdom,Europe,https://scholar.google.com/scholar?hl=en&as_sd...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"['Competency-based performance prediction', 'c...","['role', 'competencies', 'analysis', 'key', 'd..."
2,3,(ASCE)0887-3801(2006)20_3(165).pdf,Multi-Agent Framework for General-Purpose Situ...,['Models; Simulation; Construction management;...,"['Multi-agent framework', 'Situational simulat...",Journal of Computing in Civil Engineering,2006,United States,North America,https://scholar.google.com/scholar?hl=en&as_sd...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"['Multi-agent systems', 'situational simulatio...","['cm', 'events', 'operators', 'activities', 't..."
3,4,(ASCE)1532-6748(2001)1_2(17).pdf,Construction Management Practices Are Slowly C...,[],"['Strategic planning', 'Construction managemen...",Leadership and Management in Engineering,2001,NaN,4,https://scholar.google.com/scholar?hl=en&as_sd...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,['Strategic management in construction industr...,"['500', 'strategic management', 'based', 'mana..."
4,5,(ASCE)CO.1943-7862.0000100.pdf,Managerial Competencies of Female and Male Con...,['Women; Discrimination; Workplace diversity; ...,"['Female project managers', 'Managerial compet...",Journal of Construction Engineering and Manage...,2009,United States,North America,https://scholar.google.com/scholar?hl=en&as_sd...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"['Gender representation in construction', 'Man...","['competencies', 'focus', 'industry', '2009', ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000,1013,1013.pdf,Japan's building industry: The new model,['Japan; building industry; change; model buil...,"['Japanese building industry', 'Big five contr...",Construction Management and Economics,1993,United Kingdom,Europe,https://www.tandfonline.com/doi/abs/10.1080/01...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001,1014,1014.pdf,Forecasting methodology of national demand for...,['Building economics; forecasting; label stati...,"['Construction labour forecasting', 'National ...",Construction Management and Economics,1993,United States,North America,https://www.tandfonline.com/doi/abs/10.1080/01...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1002,1015,1015.pdf,Estimating industry-level productivity trends ...,['Total factor productivity; productivity; Hon...,"['Total-factor productivity', 'Building indust...",Construction Management and Economics,1993,Hong Kong,Asia,https://www.tandfonline.com/doi/abs/10.1080/01...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1003,1016,1016.pdf,Masonry productivity forecasting model,NaN,"['Masonry labor productivity', 'Productivity f...",Journal of construction engineering and manage...,1993,United States,North America,https://ascelibrary.org/doi/abs/10.1061/(ASCE)...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1004,1017,1017.pdf,Integrated construction project document manag...,['CIC; conceptual modelling; integration; docu...,"['Integrated document management', 'Computer i...",Proceedings of EuropIA,1993,Findland,Europe,https://citeseerx.ist.psu.edu/document?repid=r...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
# Filter out rows where 'Topics' is NaN
df = df.dropna(subset=['Topics'])

In [18]:
# Apply ast.literal_eval to convert string representations of lists into actual lists
df['Topics'] = df['Topics'].apply(lambda topics_list_str: ast.literal_eval(topics_list_str) if isinstance(topics_list_str, str) else topics_list_str)

In [19]:
import pandas as pd

def combine_topics(df):
    """
    Combines all topics from the 'Topics' column of the dataframe into a single set,
    treating topics as identical regardless of case.
    
    Parameters:
        df (pandas.DataFrame): A dataframe with a 'Topics' column where each entry is a list of topics.
    
    Returns:
        set: A set containing all unique topics in lower-case.
    """
    all_topics = set()
    for topics_list in df['Topics']:
        # Convert each topic to lower case and add to the set
        all_topics.update([topic.lower() for topic in topics_list])
    return all_topics

In [20]:
all_topics_set = combine_topics(df)

In [21]:
all_topics_list = list(all_topics_set)

In [22]:
len(all_topics_set)

6460

# Merge topics into broader categories

In [23]:
summarize_topics_into_broader_categories_prompt = f'''
As an expert in construction management, your task is to analyze and categorize a list of academic topics extracted from construction management journal papers. Your goal is to group similar topics into broader, more encompassing categories.

Please follow these guidelines:
1. Carefully examine each topic and its relevance to construction management.
2. Identify overarching themes or areas that can logically group multiple related topics.
3. Create broader categories that are meaningful and representative of key areas in construction management.
4. Ensure that each original topic is assigned to the most appropriate broader category.
5. Aim for a final list of less than 50 broader categories.

Your output should be a list of these broader categories, each encompassing multiple original topics. The type of the output must be a list instead of a string containing a list.

Example input: 
[Competency assessment test, Female project managers, Managerial competencies, Workplace diversity, Personnel management, Construction project management, Performance prediction, Multi-agent framework]

Example output:
[Human Resource Management in Construction, Project Management Practices, Diversity and Inclusion in Construction, Performance Evaluation and Prediction]

Here's the list (the type is list in Python) of topics to categorize into broader categories:
{all_topics_list}

Please provide your categorized list of broader topics based on this input.

'''

In [24]:
response = RoleGeneration(summarize_topics_into_broader_categories_prompt)

In [25]:
response

'```python\n[\n    "Project Management Practices",\n    "Human Resource Management in Construction",\n    "Health, Safety, and Environmental Management",\n    "Technology and Innovation in Construction",\n    "Procurement and Supply Chain Management",\n    "Risk Management in Construction",\n    "Legal and Regulatory Compliance",\n    "Financial Management and Economics",\n    "Sustainability and Green Building",\n    "Construction Scheduling and Time Management",\n    "Quality Management and Assurance",\n    "Stakeholder Engagement and Communication",\n    "Construction Site Management and Logistics",\n    "Construction Methods and Processes",\n    "Education and Training in Construction Management",\n    "Construction Information Systems and ICT",\n    "Organizational Structure and Culture in Construction Firms",\n    "Market Dynamics and Competitiveness",\n    "Performance Measurement and Evaluation",\n    "Construction Dispute Resolution",\n    "Knowledge Management and Learning in Construction",\n    "Building Information Modeling (BIM) and Digital Technologies",\n    "Construction Contract Management",\n    "Construction Automation and Robotics",\n    "Construction Supply Chain Integration",\n    "Innovation and Change Management",\n    "Construction Financial Performance",\n    "Project Financing and Funding",\n    "Construction Sustainability Practices",\n    "Construction Workforce and Labor Management",\n    "Construction Data Analytics and Predictive Modeling",\n    "Construction Simulation and Modeling",\n    "Construction Delays and Mitigation Strategies",\n    "Sustainability Assessment in Construction",\n    "Construction Technology Adoption",\n    "Construction Safety Culture",\n    "Smart Technologies in Construction",\n    "Construction Legal Systems",\n    "Construction Procurement Strategies",\n    "Construction Asset Management",\n    "Decision-Making Processes in Construction",\n    "Economic Impact of Construction",\n    "Project Complexity in Construction",\n    "Employee Engagement and Motivation in Construction",\n    "Barriers to Innovation in Construction",\n    "Construction Standards and Certifications",\n    "Integrated Project Delivery Models",\n    "Lean Construction Principles",\n    "Digital Twin and Virtual Reality Applications",\n    "Collaborative Construction Practices",\n    "Public-Private Partnerships in Construction",\n    "Construction Performance Metrics",\n    "Waste Management and Recycling in Construction"\n]\n```'

In [29]:
topics_list = ast.literal_eval('[\n    "Project Management Practices",\n    "Human Resource Management in Construction",\n    "Technology and Innovation in Construction",\n    "Risk Management in Construction",\n    "Sustainability and Environmental Management",\n    "Cost Management and Financial Analysis",\n    "Construction Planning and Scheduling",\n    "Safety Management in Construction",\n    "Supply Chain and Logistics Management",\n    "Construction Methods and Techniques",\n    "Stakeholder and Client Management",\n    "Quality Management and Assurance",\n    "Legal and Regulatory Compliance",\n    "Organizational Structure and Culture in Construction Firms",\n    "Education and Training in Construction",\n    "Construction Information Systems and ICT",\n    "Performance Measurement and Evaluation",\n    "Leadership in Construction Organizations",\n    "Conflict and Dispute Resolution",\n    "Construction Policy and Governance",\n    "Construction Design and Architectural Planning",\n    "Materials Management and Sustainability",\n    "Infrastructure and Mega-Projects Management",\n    "Construction Finance and Investment",\n    "Contract Management and Procurement",\n    "Communication and Collaboration in Construction",\n    "Market Analysis and Competitiveness",\n    "Knowledge Management in Construction",\n    "Construction Safety Technologies",\n    "Lean Construction Practices",\n    "Demolition and Waste Management",\n    "Ethics and Professionalism in Construction",\n   "Gender and Diversity in Construction",\n    "Construction Economics and Industrial Organization",\n "Building Information Modeling (BIM) and Digital Technologies",\n    "Construction Automation and Robotics",\n   "Construction Workforce and Labor Management",\n    "Construction Data Analytics and Predictive Modeling",\n    "Construction Simulation and Modeling",\n    "Construction Asset Management",\n    "Decision-Making Processes in Construction",\n    "Construction Standards and Certifications",\n    "Digital Twin and Virtual Reality Applications",\n    "Public-Private Partnerships in Construction",\n]')

print(topics_list)

['Project Management Practices', 'Human Resource Management in Construction', 'Technology and Innovation in Construction', 'Risk Management in Construction', 'Sustainability and Environmental Management', 'Cost Management and Financial Analysis', 'Construction Planning and Scheduling', 'Safety Management in Construction', 'Supply Chain and Logistics Management', 'Construction Methods and Techniques', 'Stakeholder and Client Management', 'Quality Management and Assurance', 'Legal and Regulatory Compliance', 'Organizational Structure and Culture in Construction Firms', 'Education and Training in Construction', 'Construction Information Systems and ICT', 'Performance Measurement and Evaluation', 'Leadership in Construction Organizations', 'Conflict and Dispute Resolution', 'Construction Policy and Governance', 'Construction Design and Architectural Planning', 'Materials Management and Sustainability', 'Infrastructure and Mega-Projects Management', 'Construction Finance and Investment', 'Contract Management and Procurement', 'Communication and Collaboration in Construction', 'Market Analysis and Competitiveness', 'Knowledge Management in Construction', 'Construction Safety Technologies', 'Lean Construction Practices', 'Demolition and Waste Management', 'Ethics and Professionalism in Construction', 'Gender and Diversity in Construction', 'Construction Economics and Industrial Organization', 'Building Information Modeling (BIM) and Digital Technologies', 'Construction Automation and Robotics', 'Construction Workforce and Labor Management', 'Construction Data Analytics and Predictive Modeling', 'Construction Simulation and Modeling', 'Construction Asset Management', 'Decision-Making Processes in Construction', 'Construction Standards and Certifications', 'Digital Twin and Virtual Reality Applications', 'Public-Private Partnerships in Construction']

In [32]:
len(topics_list)

44