In [1]:
import os
import re
import pandas as pd

# 1. Load topics and citation datasets

# 1.1 Extract topics from txt file and convert to dataframe

In [5]:
# Initialize an empty list to hold the file name and topics data
data = []

# Directory where the txt files are located
folder_path = '/Users/yunshunzhong/Library/Mobile Documents/3L68KQB4HG~com~readdle~CommonDocuments/Documents/PhD Project/Prompt Engineering/topics_dataset/topics_results'

In [6]:

# Loop through every file in the directory
for filename in os.listdir(folder_path):
    if filename.endswith('.txt'):  # Ensure the file is a text file
        file_path = os.path.join(folder_path, filename)

        # Open the text file and read its contents
        with open(file_path, 'r') as f:
            content = f.read()

            # Use a regular expression to find the topics
            match = re.search(r'[tT]opics: (.+)', content)

            if match:  # If a match was found
                topics_str = match.group(1)
                topics_list = [topic.strip() for topic in topics_str.split(',')]

                # Append the file name and topics to the data list
                data.append({'file_name': filename, 'topics': topics_list})

In [7]:
# Create a DataFrame from the data
df_topics = pd.DataFrame(data)
df_topics.head()

,file_name,topics
0,Exploring the status benefits barriers and opp...,"[BIM integration, Prefabrication, Construction..."
1,"[18476228 - Organization, Technology and Manag...","[Augmented Reality, Virtual Reality, Construct..."
2,Pandemics public private partnerships PPPs and...,"[Pandemics, Public-private partnerships, Force..."
3,Conceptual delay mitigation model using a proj...,"[Construction project delay, Project learning,..."
4,The rhythms of project life a longitudinal ana...,"[Work hours, Work-life balance, Project-based ..."

In [16]:
df_topics['Index'] = range(len(df_topics))

In [8]:
print(df_topics['topics'][5])

['Value agenda', 'Through-life value creation', 'Construction management', 'Integrated solutions', 'service-led projects', 'Privatization', 'Outsourcing', 'High value manufacturing', 'Servitization.']

In [9]:
# Remove . from every row of a list of topics
df_topics['topics'] = df_topics['topics'].apply(lambda topic_list: [topic.replace('.', '') for topic in topic_list])

In [10]:
print(df_topics['topics'][5])

['Value agenda', 'Through-life value creation', 'Construction management', 'Integrated solutions', 'service-led projects', 'Privatization', 'Outsourcing', 'High value manufacturing', 'Servitization']

In [11]:
# Remove .pdf from the filename strings
df_topics['file_name'] = df_topics['file_name'].str.replace('.txt', '')

/var/folders/t8/y0j5x77s7zqfzbzs7dpj9c1h0000gn/T/ipykernel_49088/2695476372.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df_topics['file_name'] = df_topics['file_name'].str.replace('.txt', '')

In [18]:

'''An example'''
# add published year to df
# published_year = [2009, 1998, 2005, 2020, 2021, 2022, 2019, 2022, 2001, 2021, 2009, 2015, 2021, 2021, 2018, 2009, 2015, 2009, 2001, 2005]
# published_region = ['Canada', 'Canada', 'Canada', 'Canada', 'Canada', 'Canada', 'Canada', 'Canada', 'Canada', 'Hong Kong', 'Canada', 'New Zealand', 'UK', 'USA', 'Norway', 'UK', 'Germany', 'NaN', 'Egypt', 'UK']
# df['published_year'] = published_year
# df['published_region'] = published_region
# # Show the DataFrame
# df.head(20)

'An example'

In [12]:
df_topics.shape

(619, 2)

In [19]:
df_topics.to_excel("/Users/yunshunzhong/Library/Mobile Documents/3L68KQB4HG~com~readdle~CommonDocuments/Documents/PhD Project/Prompt Engineering/topics_dataset/df_topics.xlsx")

# 1.2 Load citation dataset

In [2]:
citation_file_path = '/Users/yunshunzhong/Library/Mobile Documents/3L68KQB4HG~com~readdle~CommonDocuments/Documents/PhD Project/Prompt Engineering/topics_dataset/Publication_Database.xlsx'
df_citation = pd.read_excel(citation_file_path)
df_citation.head()

,Index,File_Name,Paper_Name,Keywords,Journal_Name,Published_Year,Country,Continent,URL,Given Total,...,1989,1988,1987,1986,1985,1984,1983,1982,1981,1980
0,0,(ASCE)0733-9364(1986)112_3(346).pdf,RESOURCE MANAGEMENT IN CONSTRUCTION,-1,Journal of construction engineering and manage...,1986.0,United States,North America,https://scholar.google.com/scholar?hl=en&as_sd...,89,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,(ASCE)0733-9364(1995)121_3(319).pdf,CONSTRUCTION,-1,Journal of Construction Engineering and Manage...,1995.0,United States,North America,https://scholar.google.com/scholar?hl=en&as_sd...,-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,(ASCE)0742-597X(2005)21_1(2).pdf,Competency-Based Model for Predicting Construc...,Human factors; Professional development; Proje...,Journal of Management in Engineering,2005.0,United Kingdom,Europe,https://scholar.google.com/scholar?hl=en&as_sd...,311,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,(ASCE)0887-3801(2006)20_3(165).pdf,Multi-Agent Framework for General-Purpose Situ...,Models; Simulation; Construction management; A...,Journal of Computing in Civil Engineering,2006.0,United States,North America,https://scholar.google.com/scholar?hl=en&as_sd...,73,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,(ASCE)1532-6748(2001)1_2(17).pdf,Construction Management Practices Are Slowly C...,-1,Leadership and Management in Engineering,2001.0,NaN,4,https://scholar.google.com/scholar?hl=en&as_sd...,28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# Remove .pdf from the strings
df_citation['File_Name'] = df_citation['File_Name'].str.replace('.pdf', '')

/var/folders/t8/y0j5x77s7zqfzbzs7dpj9c1h0000gn/T/ipykernel_49088/292881251.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df_citation['File_Name'] = df_citation['File_Name'].str.replace('.pdf', '')

In [4]:
df_citation.shape

(748, 55)

# 1.3 Merge topics and citation dataframes

In [13]:
import pandas as pd

# Assuming df_citation and df_topics are your DataFrames and they have 'File_Name' and 'file_name' columns respectively.

# Perform an outer join on the file names
df_outer = df_citation.merge(df_topics, left_on='File_Name', right_on='file_name', how='outer', indicator=True)

# Filter out only the rows that didn't match from both sides
df_no_match = df_outer[df_outer['_merge'] != 'both']

# Now df_no_match contains rows where file names didn't match. We can iterate through it and print the details.
for index, row in df_no_match.iterrows():
    # Check which side (left_only for df_citation, right_only for df_topics) the unmatched row comes from
    if row['_merge'] == 'left_only':
        # The row comes from df_citation
        print(f"Row {index} in df_citation with File_Name '{row['File_Name']}' did not match.")
    elif row['_merge'] == 'right_only':
        # The row comes from df_topics
        print(f"Row {index} in df_topics with file_name '{row['file_name']}' did not match.")

Row 1 in df_citation with File_Name '(ASCE)0733-9364(1995)121_3(319)' did not match.
Row 4 in df_citation with File_Name '(ASCE)1532-6748(2001)1_2(17)' did not match.
Row 7 in df_citation with File_Name '1-s2.0-S0306261915008016-main' did not match.
Row 16 in df_citation with File_Name '27' did not match.
Row 17 in df_citation with File_Name '27' did not match.
Row 18 in df_citation with File_Name '7' did not match.
Row 22 in df_citation with File_Name 'Amir Hossein_Heravi Torbati_Thesis' did not match.
Row 25 in df_citation with File_Name 'Analysing construction organizations' did not match.
Row 28 in df_citation with File_Name 'Applying advanced technology to improve safety management in the construction industry a literature review' did not match.
Row 29 in df_citation with File_Name 'ART_16_Workshop_1_Waste_discussion_Quantifying the causes and costs of rework in construction' did not match.
Row 31 in df_citation with File_Name 'Between hard and soft HRM human resource management in the construction industry' did not match.
Row 32 in df_citation with File_Name 'Bresnen-M.-and-Marshall-N.-2000a-?????Building-Partnerships-Case-Studies-of-Client-Contractor-Collaboration-in-the-United Kingdom-Construction-Industry?????' did not match.
Row 34 in df_citation with File_Name 'Choosing an appropriate research methodology' did not match.
Row 37 in df_citation with File_Name 'Contractor prequalification data for construction owners' did not match.
Row 39 in df_citation with File_Name 'Design for construction utilizing production experiences in development' did not match.
Row 44 in df_citation with File_Name 'Globalization and construction industry development implications of recent developments in the construction sector in Asia' did not match.
Row 49 in df_citation with File_Name 'Is construction project planning really doing its job A critical examination of focus role and process' did not match.
Row 51 in df_citation with File_Name 'Management of construction waste in public housing projects in China' did not match.
Row 55 in df_citation with File_Name 'Obstacles to implementing total quality management in the United Kingdom construction industry' did not match.
Row 57 in df_citation with File_Name 'POST-PEER-REVIEW-NON-PUBLISHERS.PDF' did not match.
Row 61 in df_citation with File_Name 'Re engineering construction a new management research agenda' did not match.
Row 64 in df_citation with File_Name 'risk' did not match.
Row 70 in df_citation with File_Name 'Table_of_Contents_3862' did not match.
Row 80 in df_citation with File_Name '(ASCE)CO.1943-7862.0000099' did not match.
Row 91 in df_citation with File_Name '1-s2.0-S0926580503000049-main' did not match.
Row 114 in df_citation with File_Name '86779636' did not match.
Row 115 in df_citation with File_Name 'Applications of multirotor drone technologies in construction management' did not match.
Row 117 in df_citation with File_Name 'Assessing supervision requirements of PhD students The case of construction management and engineering in the United Kingdom' did not match.
Row 124 in df_citation with File_Name 'Computer aided Civil Eng - 2002 - Yau - Case?????Based Reasoning in Construction Management' did not match.
Row 134 in df_citation with File_Name 'Leadership style of construction managers in China' did not match.
Row 138 in df_citation with File_Name 'Rethinking prefabricated construction management using the VP based IKEA model in China' did not match.
Row 150 in df_citation with File_Name 'A grounded theory of women s career under achievement in large United Kingdom construction companies' did not match.
Row 151 in df_citation with File_Name 'A linear programming model for cash flow management in the Brazilian construction industry' did not match.
Row 152 in df_citation with File_Name 'A methodology for predicting company failure in the construction industry' did not match.
Row 157 in df_citation with File_Name 'An empirical study of the benefits of construction partnering in China' did not match.
Row 159 in df_citation with File_Name 'Analysis of conflict and change in construction projects' did not match.
Row 161 in df_citation with File_Name 'Building a conceptual framework for measuring business performance in construction an empirical evaluation' did not match.
Row 162 in df_citation with File_Name 'C123cme3.PDF' did not match.
Row 164 in df_citation with File_Name 'CMEGoverningtheProjectProcess' did not match.
Row 166 in df_citation with File_Name 'Construction industry clients A survey of their attributes and project management practices' did not match.
Row 167 in df_citation with File_Name 'Construction time influencing factors the contractor s perspective' did not match.
Row 168 in df_citation with File_Name 'Constructionasamanufacturingprocess' did not match.
Row 170 in df_citation with File_Name 'Critical stressors influencing construction estimators in China' did not match.
Row 173 in df_citation with File_Name 'Critical success factors for PPP PFI projects in the United Kingdom construction industry' did not match.
Row 174 in df_citation with File_Name 'Design impact of construction fast track' did not match.
Row 176 in df_citation with File_Name 'Development of a partnering performance index PPI for construction projects in China a Delphi study' did not match.
Row 184 in df_citation with File_Name 'Innovation in the construction industry the dominant role of the environment' did not match.
Row 187 in df_citation with File_Name 'Lowest price or value Investigation of United Kingdom construction clients tender selection process' did not match.
Row 188 in df_citation with File_Name 'Main contractor experiences of partnering relationships on United Kingdom construction projects' did not match.
Row 193 in df_citation with File_Name 'Objectives and performance in construction projects' did not match.
Row 194 in df_citation with File_Name 'Organizationalstructuresintheconstructionindustry1996' did not match.
Row 199 in df_citation with File_Name 'Quest for continuous quality improvement for public housing construction in China' did not match.
Row 201 in df_citation with File_Name 'Safety risk perception in construction companies in the Pacific Northwest of the USA' did not match.
Row 204 in df_citation with File_Name 'Strategic planning for competitive advantage in construction' did not match.
Row 213 in df_citation with File_Name 'Trends in productivity improvement in the US construction industry' did not match.
Row 219 in df_citation with File_Name '1-s2.0-S0301479709003338-main' did not match.
Row 222 in df_citation with File_Name '13' did not match.
Row 238 in df_citation with File_Name 'Behaviour based safety management in China s construction industry the results of a field study' did not match.
Row 244 in df_citation with File_Name 'Construction equipment productivity estimation using artificial neural network model' did not match.
Row 246 in df_citation with File_Name 'Construction site safety in China' did not match.
Row 252 in df_citation with File_Name 'Demystifying the cost barriers to offsite construction in the United Kingdom' did not match.
Row 254 in df_citation with File_Name 'Diffusion of digital innovation in construction a case study of a United Kingdom engineering firm' did not match.
Row 257 in df_citation with File_Name 'Effectiveness of safety management strategies on safety performance in China' did not match.
Row 258 in df_citation with File_Name 'Enterprise Resource Planning in a large construction firm implementation analysis' did not match.
Row 269 in df_citation with File_Name 'Industrial renewal within the construction network' did not match.
Row 273 in df_citation with File_Name 'Institutions and institutional logics in construction safety management the case of climatic heat stress' did not match.
Row 275 in df_citation with File_Name 'Is construction an industry' did not match.
Row 278 in df_citation with File_Name 'Major characteristics of constructed products and resulting limitations of construction technology' did not match.
Row 280 in df_citation with File_Name 'Motivational_Theories_and_Thei' did not match.
Row 281 in df_citation with File_Name 'Organizational culture and TQM implementation in construction firms in Singapore' did not match.
Row 283 in df_citation with File_Name 'Perspectives of United Kingdom housebuilders on the use of offsite modern methods of construction' did not match.
Row 284 in df_citation with File_Name 'Processes maps and protocols Understanding the shape of the construction process' did not match.
Row 285 in df_citation with File_Name 'Productivity1987' did not match.
Row 286 in df_citation with File_Name 'Promoting sustainable construction waste management in China' did not match.
Row 288 in df_citation with File_Name 'Research on construction industry development at the crossroads' did not match.
Row 290 in df_citation with File_Name 'Risk under performance based contracting in the United Kingdom construction sector' did not match.
Row 293 in df_citation with File_Name 'Simulation applied to construction projects' did not match.
Row 305 in df_citation with File_Name 'The culture of the industry and the culture of research' did not match.
Row 308 in df_citation with File_Name 'The impact of anti corruption strategies on corruption free performance in public construction projects' did not match.
Row 310 in df_citation with File_Name 'The multiplicity concept in construction project planning' did not match.
Row 312 in df_citation with File_Name 'United Kingdom construction site safety discourses of enforcement and engagement' did not match.
Row 317 in df_citation with File_Name '1609505940-Total_quality_management_in_the_construction_proce (2)' did not match.
Row 319 in df_citation with File_Name 'A survey of current cost estimating practices in the United Kingdom' did not match.
Row 320 in df_citation with File_Name 'Actors and objects a socio technical networks approach to technology uptake in the construction sector' did not match.
Row 325 in df_citation with File_Name 'building-construction-illustrated-francis-d-k-ching-cassandra-adams-eadf92b' did not match.
Row 326 in df_citation with File_Name 'Chinese culture and successful implementation of partnering in Singapore s construction industry' did not match.
Row 327 in df_citation with File_Name 'Construction accident causality learning from different countries and differing consequences' did not match.
Row 330 in df_citation with File_Name 'Construction Project Management A Practical Guide to Field Construction Management' did not match.
Row 333 in df_citation with File_Name 'Dainty-A.-Briscoe-G.-and-Millett-S.-2001-?????Subcontractor-Perspectives-on-Supply-Chain-Alliances?????' did not match.
Row 336 in df_citation with File_Name 'Effective construction planning' did not match.
Row 339 in df_citation with File_Name 'Establishing quantitative indicators for measuring the partnering performance of construction projects in China' did not match.
Row 347 in df_citation with File_Name 'Last among equals a comparison of innovation in construction services and manufacturing in the United Kingdom' did not match.
Row 349 in df_citation with File_Name 'Linking corporate social responsibility and organizational performance in the construction industry' did not match.
Row 357 in df_citation with File_Name 'PerceptionsofgenderrolesandattitudestowardworkamongmaleandfemaleoperativesintheScottishconstructionindustry' did not match.
Row 362 in df_citation with File_Name 'Scheduling system for high rise building construction' did not match.
Row 366 in df_citation with File_Name 'Stakeholder management through empowerment modelling project success' did not match.
Row 368 in df_citation with File_Name 'Sustainable construction aspects of using prefabrication in dense urban environment a China case study' did not match.
Row 370 in df_citation with File_Name 'The environment the fourth construction project objective' did not match.
Row 374 in df_citation with File_Name 'United Kingdom construction skills shortage response strategies and an analysis of industry perceptions' did not match.
Row 379 in df_citation with File_Name '(ASCE)1076-0431(1996)2_1(3)' did not match.
Row 383 in df_citation with File_Name '4134' did not match.
Row 386 in df_citation with File_Name 'A study of the factors affecting construction durations in China' did not match.
Row 400 in df_citation with File_Name 'Construction industry development role of technology transfer' did not match.
Row 401 in df_citation with File_Name 'Construction industry performance improvement programmes the United Kingdom case of demonstration projects in the Continuous Improvement programme' did not match.
Row 403 in df_citation with File_Name 'Cost Escalation Schedule Overruns and Quality Shortfalls on Construction Projects The Case of Zambia' did not match.
Row 410 in df_citation with File_Name 'Design issues of using prefabrication in China building construction' did not match.
Row 412 in df_citation with File_Name 'Evaluating contractor prequalification data selection criteria and project success factors' did not match.
Row 413 in df_citation with File_Name 'General contractors relationships with subcontractors A strategic asset' did not match.
Row 414 in df_citation with File_Name 'Historical comparison of construction sectors in the United States Japan Italy and Finland using input output tables' did not match.
Row 415 in df_citation with File_Name 'Impacts of information technology on the structure of construction' did not match.
Row 417 in df_citation with File_Name 'Improvement_tools_in_the_United Kingdom_construction_industry' did not match.
Row 419 in df_citation with File_Name 'ISO 9000 standards perceptions and experiences in the United Kingdom construction industry' did not match.
Row 433 in df_citation with File_Name 'Prediction of solvency in construction companies' did not match.
Row 436 in df_citation with File_Name 'Profitability of United Kingdom construction contractors' did not match.
Row 438 in df_citation with File_Name 'Resolving the United Kingdom construction skills crisis a critical perspective on the research and policy agenda' did not match.
Row 446 in df_citation with File_Name 'Strategies for the construction sector in the information technology era' did not match.
Row 453 in df_citation with File_Name 'The discourse of Respect for People in United Kingdom construction' did not match.
Row 458 in df_citation with File_Name 'TheroleofmanagerialactionsonthecosttimeperfoormanceVernonIreland' did not match.
Row 461 in df_citation with File_Name 'Work life balance of United Kingdom construction workers relationship with mental health' did not match.
Row 468 in df_citation with File_Name '82' did not match.
Row 470 in df_citation with File_Name 'A longitudinal analysis on the relationship between construction output and GDP in China' did not match.
Row 481 in df_citation with File_Name 'CMEToTProjQual' did not match.
Row 482 in df_citation with File_Name 'Co creating social value through cross sector collaboration between social enterprises and the construction industry' did not match.
Row 490 in df_citation with File_Name 'Critical Analysis of the Key Factors Affecting Construction Labour Productivity An Indian Perspective' did not match.
Row 491 in df_citation with File_Name 'Cultural differences as an explanatory variable for adversarial attitudes in the construction industry the case of China' did not match.
Row 492 in df_citation with File_Name 'Decision models for analysis and evaluation of construction contractors' did not match.
Row 502 in df_citation with File_Name 'HendricksonBook' did not match.
Row 503 in df_citation with File_Name 'Identifying the environments of construction projects' did not match.
Row 504 in df_citation with File_Name 'Improving safety by the modification of behaviour' did not match.
Row 508 in df_citation with File_Name 'Life cycle costing and risk management' did not match.
Row 522 in df_citation with File_Name 'Reasons for delays in public projects in Turkey' did not match.
Row 526 in df_citation with File_Name 'TFP-Factor-CME' did not match.
Row 534 in df_citation with File_Name 'Total quality management practices and organizational performance the mediating roles of strategies for continuous improvement' did not match.
Row 536 in df_citation with File_Name 'Uncovering sexuality and gender an intersectional examination of women s experience in United Kingdom construction' did not match.
Row 546 in df_citation with File_Name '1-s2.0-S0263786317300029-main' did not match.
Row 552 in df_citation with File_Name '1-s2.0-S1026309812000727-main' did not match.
Row 553 in df_citation with File_Name '10-1108_02635570710734280' did not match.
Row 558 in df_citation with File_Name 'A construction project cash flow model an idiographic approach' did not match.
Row 559 in df_citation with File_Name 'A definition and valuation of the United Kingdom offsite construction sector' did not match.
Row 560 in df_citation with File_Name 'A model for the selection of the optimum crane for construction sites' did not match.
Row 570 in df_citation with File_Name 'Competition and the persistence of profits in the United Kingdom construction industry' did not match.
Row 572 in df_citation with File_Name 'Concurrent engineering in design build projects' did not match.
Row 573 in df_citation with File_Name 'Construction and economic development the case of China' did not match.
Row 574 in df_citation with File_Name 'Construction industry and economic growth in Singapore' did not match.
Row 584 in df_citation with File_Name 'Factors considered in tendering decisions by top United Kingdom contractors' did not match.
Row 591 in df_citation with File_Name 'Market structure of the construction industry in China' did not match.
Row 600 in df_citation with File_Name 'Ownership advantages disadvantages of Singapore transnational construction corporations' did not match.
Row 602 in df_citation with File_Name 'Project risk action management' did not match.
Row 607 in df_citation with File_Name 'Subcontracting in commercial and residential construction an empirical investigation' did not match.
Row 608 in df_citation with File_Name 'Sustainability and the impact of Chinese policy initiatives upon construction' did not match.
Row 611 in df_citation with File_Name 'The cost of non conformance during a highway project a case study' did not match.
Row 612 in df_citation with File_Name 'The development of the construction legal system in China' did not match.
Row 619 in df_citation with File_Name 'The strategic management of architectural practice' did not match.
Row 623 in df_citation with File_Name 'Value management practices of leading United Kingdom cost consultants' did not match.
Row 631 in df_citation with File_Name '1-s2.0-S0959652620315055-main' did not match.
Row 634 in df_citation with File_Name '10-1108_09699981311324023' did not match.
Row 635 in df_citation with File_Name '146' did not match.
Row 636 in df_citation with File_Name '146' did not match.
Row 637 in df_citation with File_Name '192298_678 Raiden PrePrint' did not match.
Row 647 in df_citation with File_Name 'Are Chinese contractors competitive in international markets' did not match.
Row 654 in df_citation with File_Name 'Classification of innovation for strategic decision making in construction businesses' did not match.
Row 657 in df_citation with File_Name 'Competencies of professional quantity surveyors A South African perspective' did not match.
Row 677 in df_citation with File_Name 'isbn951385566x' did not match.
Row 684 in df_citation with File_Name 'Multi criteria evaluation model for the selection of architectural consultants' did not match.
Row 690 in df_citation with File_Name 'Planning repetitive construction Current practice' did not match.

In [14]:
df_no_match

,Index,File_Name,Paper_Name,Keywords,Journal_Name,Published_Year,Country,Continent,URL,Given Total,...,1986,1985,1984,1983,1982,1981,1980,file_name,topics,_merge
1,1.0,(ASCE)0733-9364(1995)121_3(319),CONSTRUCTION,-1,Journal of Construction Engineering and Manage...,1995.0,United States,North America,https://scholar.google.com/scholar?hl=en&as_sd...,-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,4.0,(ASCE)1532-6748(2001)1_2(17),Construction Management Practices Are Slowly C...,-1,Leadership and Management in Engineering,2001.0,NaN,4,https://scholar.google.com/scholar?hl=en&as_sd...,28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
7,7.0,1-s2.0-S0306261915008016-main,A review on sustainable construction managemen...,"Sustainable construction management, Building ...",Applied Energy,2015.0,South Korea,Asia,https://scholar.google.com/scholar?hl=en&as_sd...,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
16,16.0,27,Strategic Manaagement in Construction,NaN,BOOK,2005.0,-,16,https://scholar.google.com/scholar?hl=en&as_sd...,194,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
17,17.0,27,Construction Economics: a new approach,NaN,BOOK,2013.0,-,17,https://scholar.google.com/scholar?hl=en&as_sd...,397,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
793,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Construction industry performance improvement ...,"[Performance improvement, UK construction indu...",right_only
794,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1-s2.0-S0950061821026568-main,"[Climate change impact, Infrastructure, Machin...",right_only
795,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1-s2.0-S2214391220303299-main,"[pavement condition index, international rough...",right_only
796,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Computer aided Civil Eng - 2002 - Yau - Case‐B...,"[Case-based reasoning, Construction management...",right_only
797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Resolving the UK construction skills crisis a ...,"[Skills crisis, Research agenda, Policy agenda...",right_only

In [2]:
# Test whether a file name in citation dataset exists in topics and all_txt folder
import os

def find_file_in_folder(target_file_name, root_folder):
    # Walk through the directory
    for subdir, dirs, files in os.walk(root_folder):
        # Check if target file exists in the list of files
        if target_file_name in files:
            # If file is found, print the subdirectory it is in
            print(f"File '{target_file_name}' found in subfolder: {subdir}")
            return
    # If file is not found after walking through all directories, print that it wasn't found
    print(f"File '{target_file_name}' not found in any subfolder of '{root_folder}'.")

# Example usage
all_txt_folder = '/Users/yunshunzhong/Library/Mobile Documents/3L68KQB4HG~com~readdle~CommonDocuments/Documents/PhD Project/Prompt Engineering/topics_dataset/all_txt_without_ref'  # Replace with the path to your 'all_txt' folder
all_pdf_folder = '/Users/yunshunzhong/VirtualEnvironments/pythonProject/tcm/tcm/collected_dataset/downloaded_papers/pdf'
file_to_find = 'Construction industry performance improvement programmes the UK case of demonstration projects in the Continuous Improvement programme'  # Replace with the file name you are looking for

find_file_in_folder(file_to_find+'.pdf', all_pdf_folder)
find_file_in_folder(file_to_find+'.txt', all_txt_folder)

File 'Construction industry performance improvement programmes the UK case of demonstration projects in the Continuous Improvement programme.pdf' found in subfolder: /Users/yunshunzhong/VirtualEnvironments/pythonProject/tcm/tcm/collected_dataset/downloaded_papers/pdf/result_page_51_60
File 'Construction industry performance improvement programmes the UK case of demonstration projects in the Continuous Improvement programme.txt' found in subfolder: /Users/yunshunzhong/Library/Mobile Documents/3L68KQB4HG~com~readdle~CommonDocuments/Documents/PhD Project/Prompt Engineering/topics_dataset/all_txt_without_ref

In [23]:
df = df_citation.merge(df_topics, left_on='File_Name', right_on='file_name', how='inner')
df.head()

,Index_x,File_Name,Paper_Name,Keywords,Journal_Name,Published_Year,Country,Continent,URL,Given Total,...,1986,1985,1984,1983,1982,1981,1980,file_name,topics,Index_y
0,0,(ASCE)0733-9364(1986)112_3(346),RESOURCE MANAGEMENT IN CONSTRUCTION,-1,Journal of construction engineering and manage...,1986.0,United States,North America,https://scholar.google.com/scholar?hl=en&as_sd...,89,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(ASCE)0733-9364(1986)112_3(346),"[Resource management, Construction industry, R...",45
1,2,(ASCE)0742-597X(2005)21_1(2),Competency-Based Model for Predicting Construc...,Human factors; Professional development; Proje...,Journal of Management in Engineering,2005.0,United Kingdom,Europe,https://scholar.google.com/scholar?hl=en&as_sd...,311,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(ASCE)0742-597X(2005)21_1(2),"[Construction project management, Competency-b...",284
2,3,(ASCE)0887-3801(2006)20_3(165),Multi-Agent Framework for General-Purpose Situ...,Models; Simulation; Construction management; A...,Journal of Computing in Civil Engineering,2006.0,United States,North America,https://scholar.google.com/scholar?hl=en&as_sd...,73,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(ASCE)0887-3801(2006)20_3(165),"[Multi-agent framework, Situational simulation...",67
3,5,(ASCE)CO.1943-7862.0000100,Managerial Competencies of Female and Male Con...,Women; Discrimination; Workplace diversity; Pe...,Journal of Construction Engineering and Manage...,2009.0,United States,North America,https://scholar.google.com/scholar?hl=en&as_sd...,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(ASCE)CO.1943-7862.0000100,"[Female project managers, Managerial competenc...",121
4,6,1-s2.0-S026378639800060X-main,Construction delay: a quantitative analysis,Construction management; Project planning; Con...,International Journal of Project Management,2000.0,Jordan,Asia,https://scholar.google.com/scholar?hl=en&as_sd...,936,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1-s2.0-S026378639800060X-main,"[Construction delay, Construction management, ...",266

In [14]:
df.shape

(577, 57)

In [34]:
df.to_pickle('/Users/yunshunzhong/Library/Mobile Documents/3L68KQB4HG~com~readdle~CommonDocuments/Documents/PhD Project/Prompt Engineering/merged_df.pkl')

## 1.4 Summarize topics again (don't need to run again)

In [15]:
all_topics = df['topics'].explode().unique().tolist()
len(all_topics)

3983

In [16]:
all_topics

['Resource management',
 'Construction industry',
 'Resource planning',
 'Cost control',
 'Project scheduling',
 'Resource allocation',
 'Critical Path Method',
 'Construction equipment',
 'Leased resources',
 'Owned resources',
 'Construction project management',
 'Competency-based model',
 'Human resource management',
 'Performance prediction',
 'Behavioral event interviews',
 'Core competencies',
 'Team leadership',
 'Self-control',
 'HRM decision making',
 'Recruitment',
 'Performance management',
 'Multi-agent framework',
 'Situational simulations',
 'Construction management',
 'Constraint satisfaction',
 'Planning',
 'Virtual Coach',
 'Educational tool',
 'Mathematical agent',
 'Logical agent',
 'Visualization agent',
 'Female project managers',
 'Managerial competencies',
 'Gender disparity',
 'Workplace diversity',
 'Discrimination',
 'Personnel management',
 'Workplace culture',
 'Women in construction',
 'Competency assessment test',
 'Construction delay',
 'Contractual terms',
 'Causes of delay',
 'Quantitative data',
 'Public projects',
 'Jordan',
 'Project planning',
 'Linear regression',
 'construction noise',
 'adverse impacts',
 'construction stages',
 'construction machines',
 'noise sensitivity',
 'job type',
 'years of working',
 'noise management planning',
 '4D dynamic management',
 'construction planning',
 'resource management',
 'site space utilization',
 '4D technology',
 'project management',
 'decision-making support',
 'data warehousing',
 'construction progress control',
 'workspace logistics',
 'site organization',
 '3D-CAD technology',
 'Construction management process reengineering',
 'Human resource planning',
 'Team-based organization',
 'Simulation',
 'BIM',
 'integrated construction management',
 'conflict analysis',
 'structural safety problems',
 'time-dependent structures analysis',
 'schedule/resource/cost conflict analysis',
 'dynamic collision detection',
 'construction proposals',
 'efficiency',
 'safety',
 'Sustainable building',
 'Life cycle assessment',
 'Environmental impacts',
 'Cradle-to-gate impacts',
 'Budgeted environmental impacts',
 'Actual environmental impacts',
 'Activity-based environmental management',
 'Sustainable target value (STV) design',
 'Small-world overlay P2P networks',
 'Flash crowds',
 'Object replication',
 'Dynamic flash crowds',
 'Structured P2P networks',
 'UK and US construction management contracting procedures',
 'comparative study',
 'construction management contracts',
 'delivery methods',
 'construction management types',
 'processes and procedures',
 'interaction between construction manager and stakeholders',
 'compensation structure',
 'first-tier contractor',
 'risk and responsibilities distribution',
 'stakeholders',
 'Geographic information system',
 'Construction project information system',
 'Rate analysis',
 'Quality control',
 'Safety',
 'Construction project risk assessment',
 'Fuzzy logic',
 'Hierarchical risk breakdown structure',
 'Common language',
 'Fuzzy set theory',
 'Cause and effect diagrams',
 'Performance measures',
 'Linguistic variables',
 'Fuzzy associative memories',
 'Risk management',
 'Uncertain construction projects',
 'Strategic flexibility',
 'Real options approach',
 'Project valuation',
 'Dynamic uncertainties',
 'Design strategies',
 'Construction cost uncertainty',
 'Option pricing models',
 'waste behaviour',
 'construction industry',
 'waste management',
 'attitudes',
 'operatives',
 'managerial commitment',
 'resources',
 'incentives',
 'knowledge',
 'insurance',
 'construction risks',
 'contractors',
 'Nigeria',
 'supply chain management',
 'industrial organization economics',
 'supply chain structure',
 'strategic procurement management',
 'Chinese construction market',
 'Construction management practice',
 'Tendering processes',
 'Contract management',
 'On-site supervision',
 'Occupational health and safety (OHS)',
 'Construction productivity',
 'Management perspective',
 'Analytical hierarchy process',
 'Planning and programming',
 'Incentives',
 'Job satisfaction',
 'Labour productivity',
 'Pre-planning and programming',
 'Productivity bonuses',
 'Site conditions',
 'construction projects',
 'behaviours',
 'financial returns',
 'green construction',
 'legislation',
 'education',
 'cultural change',
 'Construction Scheduling Education',
 'Sustainability',
 'Lean Construction',
 'Last Planner System',
 'Construction flow index',
 'Production flow quality',
 'Lean construction',
 'Measurement of flow',
 'Composite measure',
 'Process-oriented approach',
 'Repetitive construction projects',
 'Planning and controlling production flow',
 'Validation and testing',
 'Limitations',
 'Practical application',
 'Research potential',
 'Construction in developing countries',
 'Globalization',
 'Project management',
 'Sustainable construction',
 'Construction safety',
 'Cost-effectiveness',
 'Safety programme elements',
 'Resource investment',
 'Occupational injuries',
 'Safety management',
 'stakeholder management',
 'construction project management',
 'project stakeholders',
 'project success',
 'stakeholder engagement',
 'sustainability',
 'ethics',
 'relationship management',
 'risk and uncertainty management',
 'contract choice decisions',
 'Enabling innovation',
 'Measuring innovation',
 'Innovation process',
 'Leading indicators',
 'Lagging indicators',
 'Owner influence',
 'Innovation champion',
 'Lessons learned/knowledge management',
 'Upper management support',
 'Research and development',
 'Organizational climate',
 'Organizational structure',
 'Innovation potential',
 'Innovation success',
 'Programme management',
 'Mega-projects',
 'Implementation',
 'Management regulations',
 'Stakeholder coordination',
 'Quantitative targets',
 'Guideline development',
 'Case study',
 'construction time',
 'cost overruns',
 'high-rise projects',
 'Indonesia',
 'variables',
 'questionnaire survey',
 'project managers',
 'inaccuracy of material estimating',
 'project complexity',
 'delay causes',
 'design changes',
 'poor labor productivity',
 'inadequate planning',
 'factor analysis',
 'delay factors',
 'cost overrun factors',
 'equipment usage',
 'resource estimates',
 'buildability',
 'human resource shortages',
 'cost control factors',
 'environment',
 'inaccuracy of cost estimates',
 'materials cost increases due to inflation',
 'procurement options',
 'risk management',
 'project delivery method',
 'form of payment',
 'collaboration arrangements',
 'project risks',
 'risk identification',
 'risk assessment',
 'risk response',
 'project actors',
 'communication',
 'project performance',
 'Artificial intelligence',
 'Technology adoption',
 'Emerging trends',
 'IoT (Internet of Things)',
 'Cloud computing',
 'Machine learning',
 'Digital transformation',
 'Business models',
 'ISO 14000',
 'construction enterprises',
 'Singapore',
 'environmental management',
 'sustainable construction',
 'awareness',
 'readiness',
 'certifcation',
 'promotion',
 'problems',
 'Construction planning',
 'First planning',
 'Project duration',
 'Reliability',
 'Subcontractor input',
 'Predictive models',
 'Planning methods',
 'Construction time performance',
 'Supply chain management',
 'Aerospace sector',
 'Comparative study',
 'Contextual dynamics',
 'Fragmentation',
 'Small firms',
 'Self-employment',
 'Prime contracting',
 'Collaborative working',
 'Culture change',
 'Gender imbalance',
 'Swedish construction industry',
 'Competency assessment',
 'Gender stereotypes',
 'Decision making',
 'Resilience',
 'Sensitivity',
 'Participant satisfaction',
 'Management mechanisms',
 'Goal commitment',
 'Co-operation/participation',
 'Task conflict',
 'Team conflict',
 'Risk factors',
 'International construction',
 'Indian construction companies',
 'Interpretive structural modelling',
 'Political instability',
 'Poor project management',
 'Poor government responsiveness',
 'Weak legal system',
 'Building Information Modelling (BIM)',
 'Production management systems',
 'Information and Communication Systems',
 'Software systems',
 'Production planning and control',
 'Visual management',
 'Integration of Lean and BIM',
 'Requirements gathering',
 'construction delays',
 'major construction projects',
 'Thailand',
 'developing country',
 'procurement systems',
 'designers',
 'consultants',
 'lack of resources',
 'poor contractor management',
 'design delays',
 'planning and scheduling deficiencies',
 'changed orders',
 "contractors' financial difficulties",
 'multicultural and multilingual environment',
 'large number of project participants',
 'involvement of foreign designers and contractors',
 'Flexibility',
 'Project complexity',
 'Knowledge management',
 'Psychological adjustment',
 'Coping',
 'Construction project managers',
 'Work-related stress',
 'Work-related characteristics',
 'Affect state',
 'Active coping',
 'Cognitive avoidance coping',
 'Social coping',
 'Accepting responsibility',
 'Self-controlling coping',
 'cross-cultural leadership',
 'management in construction',
 'future research',
 'cultural differences',
 'leadership styles',
 'organizational culture',
 'cultural intelligence',
 'qualitative research',
 'quantitative research',
 'cultural risk',
 'Analytic hierarchy process (AHP)',
 'Transportation',
 'Housing',
 'Contractor prequalification and selection',
 'Competitive advantage',
 'Quality management',
 'laser scanning',
 'tunnel excavation',
 'geometry documentation',
 'construction management',
 'site managers',
 'collaboration',
 'design management',
 'flaws and errors in models',
 'construction site management',
 'Skills',
 'competencies',
 'managing construction refurbishment works',
 'education and training',
 'refurbishment',
 'skills',
 'Environmental management',
 'Developing countries',
 'Principles',
 'Framework for attainment',
 'Knowledge Graphs',
 'Knowledge Graph Querying',
 'Knowledge Graph Construction',
 'Applications',
 'Linked Data',
 'Knowledge Graph Management',
 "Teachers' views",
 'Construction and management',
 'Physical education curriculum',
 'Curriculum innovation',
 'Secondary field',
 'Recontextualising agents',
 'Subject content',
 'Management and delivery',
 'Teacher involvement',
 'Teacher ownership',
 'Curriculum development',
 'Innovation management',
 'Construction firms',
 'Context variables',
 'Problem solving',
 'Diffusion',
 'Differentiation',
 'Cooperative behaviour',
 'Financial strength',
 'Time needs',
 'Construction site managers',
 'Personal characteristics',
 'Effectiveness',
 'Human resource management policy',
 'Construction management literature',
 'Leadership style',
 'Continuing professional development',
 'Education level',
 'Professional body membership',
 'typology',
 'economic organization',
 'traditional procurement',
 'construction partnering',
 'strategic alliances',
 'construction framework agreements',
 'pro-market',
 'hybrid',
 'hierarchical',
 'Augmented reality',
 'Unmanned aerial vehicle (UAV)',
 'Surveillance camera',
 'AR Technology',
 'UAV Hardware',
 'AR Implementation',
 'WLAN System',
 'Educational requirements',
 'Management tools',
 'Philosophy',
 'Project delivery',
 'General contracting',
 'Engineering News Record',
 'Construction contracts',
 'Tasks',
 'Design phase',
 'Predesign phase',
 'Construction phase',
 'Bid phase',
 'Marketing and property management',
 'Curriculum',
 'Construction education programs',
 'Expert systems',
 'Construction',
 'Knowledge acquisition',
 'Knowledge sources',
 'Hardware',
 'Software',
 'Construction areas',
 'Blackboard architecture',
 'interactive system',
 'teaching construction management',
 'VIRCON',
 '3D/4D models',
 'object-oriented programming',
 'client/server configuration',
 'database management information',
 'CAD systems',
 'scheduling',
 'simulation engine',
 'cost planning',
 'cross-impact analysis',
 'student group projects',
 'dynamic learning atmosphere',
 'computer technology',
 'networking multidiscipline teams',
 'construction activities planning',
 'cost management',
 'visualizing finished product',
 'project status reporting',
 'project transaction',
 'communication processes',
 'integrated visualization systems',
 'schedule review',
 'schedule simulator',
 'P3e',
 'OPIS',
 'ISICAD',
 'integrated project planning system',
 'object-oriented database',
 'visualization of construction plans',
 'virtual reality model',
 'collaborative planning',
 'project team communication',
 'interactive learning',
 'CMIS',
 'project model',
 'project management functions',
 'visualization capability',
 'CAD programming',
 'project databank',
 'graphical simulation',
 'integrated planning system',
 'system innovations',
 'stochastic analysis',
 'model-object linkages',
 'trade-off analysis',
 'project planning and tendering',
 'Strategic-Operational balance',
 'Hybrid simulation model',
 'Management actions',
 'Process performance improvement',
 'Earthmoving process',
 'Truck circulation rate',
 'Cost and schedule performance',
 'Integrated strategic-operational approach',
 'Cloud-enabled indoor localization',
 'RFID',
 'Asset management',
 'Remote monitoring',
 'Data visualization',
 'Latency',
 'Scalability',
 'relationship conflict',
 'performance',
 'productivity',
 'trust building',
 'antecedents',
 'consequences',
 'schedule delays',
 'lowered morale',
 'reduced profit',
 'employability',
 'graduate students',
 'training gaps',
 'perceptions',
 'statistical analysis',
 'principal-component analysis',
 'analysis of variance',
 'intrinsic reasons',
 'economic policies',
 'labor market structure',
 'business management',
 'Building information modeling (BIM)',
 'Process-oriented teaching',
 'Construction education',
 'BIM implementation',
 'BIM in plan execution',
 'BIM as a process improvement',
 'BIM software',
 'Delay studies',
 'Root cause analysis',
 'Action research',
 'Constructive research',
 'Practical recommendations',
 'Management practice',
 'Prescriptive research',
 'Descriptive research',
 'Unmanned aerial systems',
 'Visual assets',
 'Project progress monitoring',
 'Job site logistics',
 'Safety conditions',
 'Quality inspection',
 'Cost implications',
 'Regulatory environment',
 'Health monitoring',
 'Web-based system',
 'Safety and health management',
 'Performance assessment',
 'Database systems',
 'Knowledge base',
 'Benchmarking',
 'Construction professional services',
 'Knowledge structure',
 'Competency of construction management consultants',
 'Knowledge disciplines in construction management',
 '4D CAD model',
 'Integrated safety management',
 'Working-at-height hazards',
 'Safety measures',
 'Construction schedule visualization',
 'Construction design and planning',
 'Safety control',
 'Construction project evaluation',
 'Data warehouse',
 'Decision Support System',
 'OLAP',
 'Data modeling',
 'Multidimensional data cube',
 'Front-end interface',
 'Query processing',
 'Graphical display',
 'Inventory decision-making',
 'Mobile computing',
 'End user computing',
 'Inspection system',
 'Checklist system',
 'Position check system',
 'Progress monitoring system',
 'User interface formats',
 'EUC',
 'Data input',
 '4D site management',
 '3D modeling',
 'Scheduling',
 'Visualization',
 'Decision-making support',
 'Data integration',
 'Work breakdown structure',
 'Evolutionary support vector machine',
 'Fast messy genetic algorithms',
 'Object-oriented computer technique',
 'Decision support system',
 'Construction cost estimation',
 'Optimization',
 'Uncertainty',
 'Visual analytics',
 'Data representations',
 'Performance analysis',
 'Change order management',
 'Interactive interfaces',
 'Data transformation',
 'Construction project performance',
 'Construction data',
 'Metaheuristics',
 'Engineering',
 'Cost estimation',
 'Monitoring and control',
 'nD technology',
 'integrated construction management system',
 'rail transit construction',
 'information exchange',
 'multidimensional modeling',
 'Work Breakdown Structures (WBS)',
 'construction code structures',
 'information integration',
 'visualization technology',
 'web services',
 'schedule management',
 'safety management',
 'Building Information Model (BIM)',
 'Quantity take off',
 'Work processes',
 'BIM-based tool implementation strategies',
 'Technology pull',
 'Project management methods',
 'Cost estimating',
 '4D models',
 'on-site construction management',
 'mobile computing technology',
 'site monitoring',
 'task management',
 'real-time information sharing',
 'digital map',
 'augmented reality',
 'smartphone technology',
 'construction project information',
 'construction site image data',
 'lean construction management',
 'information flow',
 'communication framework',
 'Internet of Things',
 'O-MI/O-DF standards',
 'building lifecycle management',
 'enhanced construction management system',
 'interoperability',
 'system integration',
 'Power plant economics',
 'Megaprojects',
 'Schedule and cost performance',
 'Fisher Exact test',
 'Power plant characteristics',
 'Modularization',
 'Project governance',
 'External stakeholders',
 'Special Purpose Entity (SPE)',
 'Technology',
 'Formal project management approach',
 'Time-cost-quality trade-off',
 'Multi-objective optimization',
 'Evolutionary algorithms',
 'Discrete decision space',
 'Nondominated sorting genetic algorithm',
 'Multi-objective particle swarm optimization',
 'TCQTO problem',
 'TCTO problem',
 'Pareto-front',
 'project feasibility study',
 'sustainable development',
 'economic performance',
 'social performance',
 'environmental performance',
 'Chinese construction industry',
 'project participants',
 'government role',
 'project owners',
 'architects and engineering consultants',
 'contractors and suppliers',
 'Sustainable construction management',
 'Systematic literature review',
 'Sustainability in construction',
 'Environmental aspects',
 'Quantitative methodologies',
 'Bibliometric analysis',
 'VOSviewer software',
 'Economic impacts',
 'Construction management curriculum',
 'Integration of BIM',
 'Education',
 'Barriers to integration',
 'Pakistani universities',
 'decision making',
 'AHP method',
 'expert choice approach',
 'multi-criteria decision making',
 'contractor assessment',
 'project constraints',
 'Blockchain',
 'Building information modelling',
 'Information systems',
 'Intellectual property rights',
 'Trust',
 'construction management research',
 'methodology',
 'postmodernity',
 'triangulation',
 'Last Planner System implementation',
 'site management',
 'lean construction',
 'action research',
 'benefits',
 'critical success factors',
 'barriers',
 'supplier selection',
 'multi-criteria decision-making',
 'grey numbers',
 'DEMATEL',
 'BWM',
 'CoCoSo-G',
 'construction supply chain management',
 'Critical Chain',
 'Comparative Analysis',
 'Construction Management',
 'Production Control',
 'Project Management',
 'Flow Conceptualization',
 'Variability Reduction',
 'Buffer Management',
 'Task Execution',
 'Planning Techniques',
 'Synthesis',
 'Toyota Way model',
 'Implementation framework',
 'Project performance',
 'Case studies',
 'Strengths',
 'weaknesses',
 'opportunities',
 'threats',
 'SWOT analysis',
 'Contractor selection',
 'Criteria',
 'Theoretical frameworks',
 'Cost consideration framework',
 'TOPSIS and SAW-G grey techniques',
 'Prequalification method',
 'Construction management at risk method',
 'Actual criteria',
 'Contractor evaluation',
 'virtual reality',
 'digital twin',
 'online education',
 'digital pedagogy',
 'e-learning',
 'collaborative environment',
 'student engagement',
 'innovative construction management methods',
 'lean implementation',
 'project planning systems',
 'communication and coordination',
 'root causes of failure',
 'perceptive strengths and weaknesses',
 'requirements for successful implementation',
 'recommendations for improvement',
 'Construction planning and scheduling',
 'Critical Path Method (CPM)',
 'Program Evaluation and Review Technique (PERT)',
 'Bar charts',

In [17]:
all_topics_first_half = all_topics[:2000]
all_topics_second_half = all_topics[2000:]

In [18]:
import pickle
folder_path = '/Users/yunshunzhong/Library/Mobile Documents/3L68KQB4HG~com~readdle~CommonDocuments/Documents/PhD Project/Prompt Engineering'

with open(os.path.join(folder_path, "all_topics_second_half"), 'wb') as file:
    pickle.dump(all_topics_second_half, file)

In [67]:
with open(os.path.join(folder_path, "all_topics"), 'rb') as f:
    loaded_all_topics = pickle.load(f)

# 1.5 Create a topics map after summarize again

In [26]:
# second half of topics
folder_path = '/Users/yunshunzhong/Library/Mobile Documents/3L68KQB4HG~com~readdle~CommonDocuments/Documents/PhD Project/Prompt Engineering'
with open(os.path.join(folder_path, "all_topics_merged_second_half.txt"), 'r') as file:
    text = file.read()

# Split the text by 'Group'
sections = text.split("Group")[1:]  # Ignore the first empty split

# Dictionary to hold the topics and their corresponding sub-topics
topics_dict = {}

# Process each section to extract the topic and sub-topics
for section in sections:
    lines = section.strip().split('\n')
    topic = lines[0].split(":")[1].strip()  # Extract topic
    sub_topics = [line.split('-')[1].strip() for line in lines[1:]]  # Extract sub-topics
    topics_dict[topic] = sub_topics

# Print the resulting dictionary
for topic, sub_topics in topics_dict.items():
    print(topic, ":", sub_topics)
    print()

Materials Management : ['Automated materials management', 'Materials management', 'Inventory control', 'Purchasing']

Logistics and Supply Chain Management : ['Construction logistics', 'On', 'Off', 'Consolidation', 'Construction supply chain', 'Logistic']

Risk Management : ['Risk identification', 'Management risks', 'Technical risks', 'Green team risks', 'Green materials risks', 'Regulatory and economic risks']

Safety and Occupational Health : ['safety climate', 'safety leadership', 'accidents in construction industry', 'construction workers', 'self', 'safety audits', 'construction site safety', 'occupational health and safety']

Construction Cost and Productivity : ['Housing refurbishment', 'Cost reduction', 'Construction characteristics', 'Construction industry sustainability', 'Construction project delays', 'Economic growth', 'Lean principles', 'Industrialized housing production', 'Construction project culture', 'Cash flow analysis', 'Labour performance', 'Revenue risk', 'Cost of quality', 'Performance metrics', 'Performance', 'Maintenance', 'Building project', 'Productivity growth', 'productivity monitoring']

Organizational Management and Strategy : ['Strategic management', 'Role formation', 'Project file', 'Strategic planning', 'Construction firm performance', 'Benchmarking models', 'Technological attributes', 'Strategic thrusts', 'Human management', 'Maintenance management', 'Systems approach', 'Construction management evaluation', 'People aspects of KM', 'Contractor performance', 'Organizational effectiveness', 'Attitude towards change', 'Knowledge tools', 'Value management', 'Organizational justice', 'Organizational commitment', 'Knowledge transfer', 'Corporate image', 'Organizational culture', 'Organizational justice']

Construction Technology and Innovations : ['Data Envelopment Analysis (DEA)', 'Prefabricated construction', 'BIM (building information modeling)', 'Construction project delays', '3D printing', 'Digital systems integration', 'Structural safety analysis', 'Design for security', 'Energy conservation', '4D visualization', 'Internet of Things (IoT)', 'Digital infrastructure', 'Construction simulation', 'Lean production management', 'Integrated construction simulation', 'Data handover', 'Building information models', 'BIM education', 'Integrated maintenance monitoring', 'Safety compliance checking', 'Work structuring', 'Agile project management', 'Research trend', 'Industrialization level', 'Economic interdependencies', 'Construction engineering and management', 'behavioural safety', 'Building design process', 'Design integration']

Construction Contracts and Legal Issues : ['Delay analysis', 'Delay categorization', 'Power', 'Power sharing', 'Power', 'Expert power', 'Procurement method selection', 'Power disposition', 'Power gap', 'Law', 'Contractual dispute avoidance', 'labor market', 'Commercial return', 'Alternative dispute resolution', 'Contract management', 'Opposition', 'Partnership']

Construction Project Management : ['Construction delays', 'Construction project delays', 'Time and cost overruns', 'Delayed decision', 'Inaccurate time estimation', 'Poor cost estimation', 'Financial constraints', 'Future work', 'Concession period design', 'Construction project examples', 'Government regulations', "Project manager's ignorance and lack of knowledge", 'Multi', 'Project alliancing', 'Interface Management', 'Agile project management', 'European housing construction', 'Occupation safety and health', 'Project', 'Construction project conflicts', 'Construction stage', 'Work', 'Construction project implementation', 'Contracts', 'Informal sector', 'Construction site mapping', 'Project management functions', 'Project organization']

Construction Economics and Finance : ['Industry prospect', 'Economic growth', 'Causality links', 'Economic development', 'Granger causality test', 'Macroeconomy', 'Economic role', 'Financial closing', 'Inflation rate', 'Investment risk', 'International construction markets', 'Public', 'financial risks', 'Revenue dependent infrastructure projects', 'ExxonMobil Costs']

Construction and Culture : ['Social practices', 'Social performance', 'Social sustainability', 'Circular economy', 'Occupational stress', 'Cultural diversity', 'Racism', 'Gender disparities', 'Ethnic minorities']

Construction Education and Training : ['Vocational training', 'Quality assurance', 'On the job training', 'Graduate study', 'Undergraduate students', 'Skilled occupations', 'Construction skills crisis', 'Labour market']

Construction Planning and Control : ['Construction project planning and control', 'Time', 'Construction site layout planning', 'Design variation', 'Unrealistic schedules', 'Government permits', 'Poor site management', 'Construction project overhead expenses', 'Construction project goals', 'Construction project files', 'Project life cycle', 'Delay analysis', 'Construction site operations', 'Workflow management', 'Construction progress meetings', 'Risk of falls', "Analysis of contractors' pricing behavior", 'Specification', 'job satisfaction', 'Construction project culture', 'Supply chain issues', 'trade']

Sustainable Construction : ['Sustainability assessment', 'Construction industry culture', 'Sustainable urban housing', 'Building sustainability', 'Green construction', 'Sustainable construction management', 'Sustainable design']

Construction Disputes and Claims : ['Dispute resolution', 'Construction disputes', 'Construction project conflicts', 'Joint ventures', 'Claims administration', 'Contractual dispute avoidance', 'Covid', 'Force majeure provision', 'Contractual terms and conditions']

Construction Site Safety and Health : ['Safety risk interactions', "construction workers' health", 'Occupational health', 'COVID', 'Pandemics', 'safety regulations', 'Construction site safety', 'Building site', 'Safety communication', 'Health and safety']

International Construction and Global Market : ['International construction', 'International comparability', 'International business distribution', 'Colonial link', 'Global marketplace', 'Global', 'Global procurement', 'Internationalization', 'International construction joint ventures', 'International revenue', 'International competitiveness', 'International construction markets', 'International business', 'Multinational enterprise', 'International construction projects', 'International and local contractors']

Construction and Human Resource Management : ['Human resource planning', 'Employee involvement', 'Employee resourcing', 'Construction workforce', 'Recruitment', 'Training programs', 'Organizational barriers', 'Employee training and development', 'Human resource capability', 'Human resource strategies', 'skill of labor', 'Qualifications', 'Workforce composition', 'Coping strategies', 'Employee commitment', 'Occupational strain', 'Human management']

Construction Performance Measurement and Evaluation : ['Performance improvements', 'Performance metrics', 'Efficiency improvement', 'Construction firm performance', 'Construction performance measurement', 'Project performance', 'Performance', 'Maintenance', 'Performance variables', 'Maintenance management']

Innovation in Construction : ['Lean principles', 'Industrialized housing production', 'Construction innovation', 'Behavior of clients', 'Technological change', 'Innovation competence', 'Technological factors', 'Building information modeling (BIM)', 'Innovative activity', 'Routine work', 'Innovation diffusion process', 'Technological innovation', 'Innovative design', 'Innovativeness', 'Construction industry innovation']

Construction Quality Management and Assurance : ['Service quality', 'Customer loyalty', 'Quality function deployment', 'Quality management system', 'Customer satisfaction', 'Quality performance', 'Quality assurance', 'Quality of treatment', 'Quality costs', 'Customer orientation', 'Quality', 'Quality improvement', 'Quality culture']

Construction and Social Issues : ['Workplace diversity', 'Social identity', 'Safety climate', 'Socio', 'Cultural difference measurement', 'Cultural distance', 'Work', 'Social practices']

Construction Project Risk Management : ['Risk identification', 'Risk management practices', 'Construction project risk management', 'Risk analysis', 'Risk management techniques', 'Risk reduction', 'Risk transfer', 'Risk retention', 'Risk elimination', 'Construction risks']

Construction Ethics and Governance : ['Ethical practices', 'Ethical decision', 'Organizational justice', 'Construction ethics', 'Moral evaluation', 'Ethicality', 'Business ethics', 'Ethical issues', 'Ethics in construction']

Construction and Digital Technologies : ['Information communication technologies (ICT)', 'Use of ICT', 'Construction project management software', 'Building information modeling', 'Digital production', 'Digital manufacturing', 'Knowledge management systems', 'Digital innovation', 'Digital infrastructure', 'Digital transformation']

Construction and Economic Factors : ['Economic growth', 'Economic development', 'Currency risks', 'Financial risks', 'Investment risk', 'Inflation rate', 'Market risks', 'Economic implications', 'GNP', 'Construction demand', 'Macroeconomy']

Construction and Legal Issues : ['Public', 'BOT projects', 'Contractual provisions', 'Construction contracts', 'Legal risks', 'Construction project contracts', 'International contracts', 'Contractual relationships', 'Commercial contracts', 'Legal implications']

Construction and Industry Specific Factors : ['UK construction industry', 'Swedish case study', 'Construction industry in Algeria', 'Construction industry in Australia', 'Australian construction industry', 'Construction industry in Iran', 'Indonesian construction industry', 'Construction industry in Malaysia', 'French construction', 'Turkish construction sector', 'Greek']

Construction and Workplace Environment : ['Occupational health and safety', 'Work', 'Workplace stress', 'Workplace diversity', 'Work environment', 'Workload', 'Occupational stress', 'Work', 'Work']

Construction Education and Research : ['Construction education', 'Construction research', 'Information systems', 'Research methods', 'Program analysis', 'Research trends', 'Exploratory factor analysis', 'Construction management research', 'Knowledge management research']

In [27]:
len(topics_dict)

30

In [28]:
# Input text

with open(os.path.join(folder_path, "all_topics_merged_first_half.txt"), 'r') as file:
    text = file.read()

# Split the text by 'Group'
sections = text.split("Group")[1:]  # Ignore the first empty split

# Dictionary to hold the topics and their corresponding sub-topics
topics_dict2 = {}

# Process each section to extract the topic and sub-topics
for section in sections:
    lines = section.strip().split('\n')
    topic = lines[0].split(":")[1].strip()  # Extract topic

    # Extract sub-topics, ensuring we only try to split lines that contain a '-'
    sub_topics = [line.split('-')[1].strip() for line in lines[1:] if '-' in line]

    topics_dict2[topic] = sub_topics

# Print the resulting dictionary
for topic, sub_topics in topics_dict2.items():
    print(topic, ":", sub_topics)
    print()

Resource Management : ['Resource management', 'Resource planning', 'Resource allocation', 'Leased resources', 'Owned resources', 'Construction equipment', 'Constraint satisfaction', 'Resource management', 'Resource planning', 'Resource allocation']

Project Management : ['Construction project management', 'Performance prediction', 'Multi', 'Situational simulations', 'Project planning', 'Project management', 'Decision', 'Data warehousing', 'Construction progress control', 'Construction management process reengineering', 'Integrated construction management', 'Construction project risk assessment', 'Risk management', 'Integrated construction management', 'Construction management process reengineering', 'Construction project risk assessment', 'Risk management']

Human Resource Management : ['Competency', 'Human resource management', 'Behavioral event interviews', 'Core competencies', 'Team leadership', 'Self', 'HRM decision making', 'Recruitment', 'Performance management', 'Competency assessment test', 'Female project managers', 'Managerial competencies', 'Workplace diversity', 'Discrimination', 'Personnel management', 'Women in construction', 'Human resource planning', 'Team']

Construction Industry : ['Construction industry', 'Jordan', 'Construction noise', 'Construction delay', 'Causes of delay', 'Public projects', 'Construction industry', 'Jordan', 'Construction noise', 'Construction delay', 'Causes of delay', 'Public projects']

Sustainable Construction : ['Sustainable building', 'Life cycle assessment', 'Environmental impacts', 'Budgeted environmental impacts', 'Actual environmental impacts', 'Activity', 'Sustainable target value (STV) design']

Construction Contracts and Procurement : ['UK and US construction management contracting procedures', 'Comparative study', 'Construction management contracts', 'Delivery methods', 'Construction management types', 'Processes and procedures', 'Interaction between construction manager and stakeholders', 'Compensation structure', 'First', 'Risk and responsibilities distribution', 'Geographic information system', 'Construction project information system', 'Rate analysis', 'Quality control', 'Safety', 'Construction project risk assessment', 'Fuzzy logic', 'Hierarchical risk breakdown structure', 'Common language', 'Fuzzy set theory', 'Cause and effect diagrams', 'Performance measures', 'Linguistic variables', 'Fuzzy associative memories']

Construction Waste Management : ['Waste behaviour', 'Waste management', 'Attitudes', 'Operatives', 'Managerial commitment', 'Resources', 'Incentives', 'Knowledge', 'Construction risks', 'Contractors', 'Construction waste', 'Waste management', 'Attitudes', 'Construction risks', 'Contractors']

Supply Chain Management : ['Supply chain management', 'Industrial organization economics', 'Supply chain structure', 'Strategic procurement management', 'Chinese construction market', 'Supply chain management', 'Chinese construction market']

Occupational Health and Safety : ['Occupational health and safety (OHS)', 'Construction productivity', 'Analytical hierarchy process', 'Planning and programming', 'Incentives', 'Job satisfaction', 'Labour productivity', 'Occupational health and safety (OHS)', 'Construction productivity']

Lean Construction : ['Lean Construction', 'Last Planner System', 'Construction flow index', 'Production flow quality', 'Lean construction', 'Last Planner System']

Stakeholder Management and Project Success : ['Stakeholder management', 'Construction project management', 'Project stakeholders', 'Project success', 'Stakeholder engagement', 'Relationship management', 'Risk and uncertainty management', 'Contract choice decisions']

Innovation in Construction : ['Enabling innovation', 'Measuring innovation', 'Innovation process', 'Leading indicators', 'Lagging indicators', 'Owner influence', 'Innovation champion', 'Lessons learned/knowledge management', 'Upper management support', 'Research and development', 'Organizational climate', 'Organizational structure', 'Innovation potential', 'Innovation success']

Mega-projects and Program Management : ['Programme management', 'Mega', 'Implementation', 'Management regulations', 'Stakeholder coordination']

Construction Delays and Cost Overruns : ['Construction delay', 'Contractual terms', 'Causes of delay', 'Quantitative data', 'Jordan', 'Construction planning', 'Construction delay', 'Causes of delay']

Artificial Intelligence and Technology Adoption : ['Artificial intelligence', 'Technology adoption', 'Emerging trends', 'IoT (Internet of Things)', 'Cloud computing', 'Machine learning', 'Digital transformation', 'Business models']

Environmental Management : ['ISO 14000', 'Singapore', 'Environmental management', 'Environmental impacts', 'Cradle', 'Environmental management', 'Environmental impacts']

Construction Planning and Scheduling : ['Construction planning', 'Construction scheduling', 'Project scheduling', 'Critical Path Method', 'Construction planning', 'Construction scheduling']

Risk Management in Construction : ['Risk management', 'Uncertain construction projects', 'Strategic flexibility', 'Real options approach', 'Project valuation', 'Dynamic uncertainties', 'Design strategies', 'Risk management']

Geographic Information System (GIS) and Construction Project Information System : ['Geographic information system', 'Construction project information system', 'Rate analysis', 'Quantity control', 'Quality control']

Simulation and Modeling : ['Simulation', 'BIM', 'Integrated construction management', 'Conflict analysis', 'Structural safety problems', 'Time', 'Schedule/resource/cost conflict analysis', 'Dynamic collision detection', 'Simulation', 'Integrated construction management']

Construction Cost Management : ['Construction cost uncertainty', 'Option pricing models', 'cost control', 'construction cost', 'construction industry', 'cost management', 'materials cost increases due to inflation', 'cost overrun', 'cost control', 'construction cost']

Education and Training in Construction Management : ['Construction education programs', 'Training gaps', 'Perceptions', 'Statistical analysis', 'Principal', 'Analysis of variance', 'statistical analysis', 'Perceptions']

Building Information Modeling (BIM) : ['Building Information Modelling (BIM)', 'BIM (Building Information Modeling)', 'Integration of BIM', 'BIM implementation', 'BIM software', 'Integrated construction management']

Construction Safety Management : ['Construction safety', 'Cradle', 'Environmental impacts', 'Safety programme elements', 'Safety management', 'Safety and health management', 'safety management', 'Safety programme elements']

Construction Skills and Cross-cultural Leadership : ['Cross', 'Management in construction', 'Future research', 'Cross']

Technological Innovations in Construction : ['Technological innovations', 'Development', 'Diffusion', 'Technological innovations']

Building Design and Management : ['Architectural design', 'Design errors', 'Design management', 'Building design and management', 'Design errors']

Construction of Sustainable Buildings and Infrastructure : ['Sustainable buildings and infrastructure', 'Building design and management']

Knowledge Management in Construction : ['Tacit knowledge', 'Explicit knowledge', 'Knowledge management', 'Knowledge acquisition', 'Knowledge sources', 'Construction', 'Explicit knowledge']

Construction Innovation and Technology Adoption : ['Technological innovation', 'Diffusion', 'Innovation process', 'Leadership', 'Technological innovation']

Construction Performance Measurement : ['Performance measurement', 'Balanced scorecard', 'Strategy deployment', 'Performance measures', 'Building information modeling (BIM)', 'Performance measurement']

Construction Conflict and Negotiations : ['Conflict in construction industry', 'Conflict management', 'Conflict in construction industry']

Construction Safety and Hazard Management : ['Construction hazard assessment', 'Construction site analysis', 'Construction hazard identification']

Construction and Building Regulations : ['Construction legislation', 'Construction industry regulations']

Construction Labor Productivity : ['Construction labor productivity', 'Craft workers', 'Foremen', 'Construction productivity']

Construction Process Improvement : ['Construction process improvement', 'Process improvement', 'Construction waste management', 'Waste minimization', 'Construction process improvement']

Construction Information and Communication Technology (ICT) : ['Information and communication technology', 'ICT adoption', 'ICT implementation', 'Construction Information Modeling (BIM) education', 'Construction information management', 'Construction information and communication technology']

Construction Risk Management : ['Construction project risk assessment', 'Risk management (2)', 'Construction project risk assessment']

Modular and Prefabricated Construction : ['Modular integrated construction', 'Construction waste management', 'Building design and management']

Stakeholder Analysis and Management : ['Construction project management', 'Project stakeholders', 'Stakeholder management', 'Stakeholder analysis']

Economic Factors in Construction : ['Construction industry development', 'China', 'Economic reform', 'Construction output', 'Economic factors']

Productivity Improvement in Construction : ['Construction labor productivity', 'Labor supervision', 'Labor experience and skills', 'Construction technology']

Stakeholder Engagement and Collaboration : ['Stakeholder engagement', 'Collaboration', 'Stakeholder management']

Risk Assessment and Management Systems : ['Risk management', 'Risk assessment', 'Risk management']

Knowledge Acquisition and Management in Construction : ['Knowledge acquisition', 'Knowledge management']

Construction Education and Training : ['Construction education programs', 'Training and skill development']

Construction Procurement : ['PPP contracts', 'Tender selection']

Quality Control in Construction : ['Quality control', 'ISO 9000']

Occupational Health and Safety in Construction : ['Occupational health and safety (OHS)', 'Safety', 'Safety management']

Lean Construction and Production Management : ['Lean Construction', 'Production management systems', 'Lean construction']

Construction Project Risk Assessment : ['Construction project risk assessment', 'Risk management']

Construction Procurement and Contract Management : ['Construction contracts', 'Contract management']

Construction Performance Improvement : ['Performance improvement', 'Process improvement']

Occupational Health and Safety Management Systems : ['Occupational health and safety (OHS)', 'Safety management']

Construction Planning and Execution : ['Construction planning', 'Project execution']

Construction Evolution and Technological Trends : ['Technological trends', 'Construction future studies']

Innovations in Construction Processes : ['Innovations', 'Construction processes']

Sustainability in Construction : ['Sustainable construction', 'Sustainability']

Construction Project Performance Measurement : ['Construction project performance measurement', 'Performance measurement']

Construction Information and Knowledge Management : ['Construction project information system', 'Knowledge management']

Construction Hazard Management : ['Construction hazard identification', 'Construction hazard assessment']

Construction Productivity Management : ['Construction productivity', 'Labour productivity']

Lean Construction and Project Performance : ['Lean Construction', 'Project performance']

Construction Safety Culture : ['Construction safety culture', 'Safety culture']

Sustainable Construction and Building Design : ['Sustainable construction', 'Building design']

Construction Training and Skill Development : ['Construction skills training', 'Training and skill development']

Construction Safety Programs : ['Safety programs', 'Safety programme elements']

Construction Occupational Health and Safety : ['Occupational health and safety (OHS)', 'Construction safety']

Construction Performance Measurement Systems : ['Performance measurement systems', 'Performance measures']

Construction Supply Chain : ['Supply chain management', 'Construction supply chain management']

Construction Waste Reduction : ['Waste reduction', 'Construction waste']

Construction Knowledge Management : ['Knowledge management', 'Construction industry knowledge']

Construction Management Contracts : ['Construction management contracts', 'Construction management (2)']

Construction Project Procurement : ['Project procurement', 'Procurement systems']

Construction Time and Cost Control : ['Time control', 'Cost control']

Construction Labor Shortages : ['Construction labor force', 'Labor shortages']

Construction Project Delivery Methods : ['Project delivery methods', 'Delivery methods']

Construction Management and Operations : ['Construction management', 'Construction operations']

Construction Equipment Management : ['Construction equipment', 'Equipment management']

Construction Project Communication : ['Construction communication', 'Project information']

Construction Labor and Workforce Management : ['Construction workforce', 'Labor management']

Construction Performance Improvement Programs : ['Performance improvement programs', 'Process improvement programs']

Construction Project Tracking and Monitoring : ['Project progress monitoring', 'Project tracking and monitoring']

Construction Contract Management : ['Contract management']

Construction Performance and Benchmarking : ['Performance assessment', 'Benchmarking']

Construction Equipment and Material Management : ['Construction equipment', 'Construction materials']

Construction Project Risk Assessment and Management : ['Construction project risk assessment', 'Risk assessment']

Construction Innovation and Process Improvement : ['Innovation in construction', 'Process improvement']

Construction Project Communication and Coordination : ['Construction project communication', 'Project coordination']

Construction Project Delivery and Management : ['Project delivery', 'Project management']

Construction Project Performance Evaluation : ['Construction project evaluation', 'Project performance']

Construction Planning and Design : ['Construction planning', 'Design phase', 'Construction phase', 'Design phase']

Construction Project Delays and Cost Overruns : ['Construction delay', 'Design changes', 'Poor labor productivity', 'Inadequate planning', 'Construction project delays', 'Construction project delays']

Construction Project Delivery and Performance : ['Project delivery', 'Project performance']

Construction Project Risk Assessment and Mitigation : ['Construction project risk assessment', 'Risk assessment']

Construction Procurement and Supply Chain Management : ['Construction procurement', 'Supply chain management']

Construction Project Simulation and Visualization : ['Simulation', 'Visualization', 'Construction project simulation']

Construction Planning and Execution Control : ['Construction planning', 'Construction execution control']

Construction Project Visualization and Communication : ['Visualization', 'Communication', 'Construction project visualization']

Construction Risk Management and Project Performance : ['Risk management', 'Project performance']

In [29]:
len(topics_dict2)

100

In [30]:
# Merge two dictionaries together
'''
Example input:
{Human Resource Management : ['Competency', 'Human resource management']}
{Human Resource Management : ['Behavioral event interviews', 'Core competencies', 'Team leadership']}
Example output:
{Human Resource Management : ['Competency', 'Human resource management', 'Behavioral event interviews', 'Core competencies', 'Team leadership']}
'''
for key, value in topics_dict2.items():
    if key in topics_dict:
        topics_dict[key].extend(value)
    else:
        topics_dict[key] = value

len(topics_dict)

127

# 1.6 Map summarized topics back to original dataframe

In [24]:
df.head()

,Index,File_Name,Paper_Name,Keywords,Journal_Name,Published_Year,Country,Continent,URL,Given Total,...,1987,1986,1985,1984,1983,1982,1981,1980,file_name,topics
0,0,(ASCE)0733-9364(1986)112_3(346),RESOURCE MANAGEMENT IN CONSTRUCTION,-1,Journal of construction engineering and manage...,1986.0,United States,North America,https://scholar.google.com/scholar?hl=en&as_sd...,89,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(ASCE)0733-9364(1986)112_3(346),"[Resource management, Construction industry, R..."
1,2,(ASCE)0742-597X(2005)21_1(2),Competency-Based Model for Predicting Construc...,Human factors; Professional development; Proje...,Journal of Management in Engineering,2005.0,United Kingdom,Europe,https://scholar.google.com/scholar?hl=en&as_sd...,311,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(ASCE)0742-597X(2005)21_1(2),"[Construction project management, Competency-b..."
2,3,(ASCE)0887-3801(2006)20_3(165),Multi-Agent Framework for General-Purpose Situ...,Models; Simulation; Construction management; A...,Journal of Computing in Civil Engineering,2006.0,United States,North America,https://scholar.google.com/scholar?hl=en&as_sd...,73,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(ASCE)0887-3801(2006)20_3(165),"[Multi-agent framework, Situational simulation..."
3,5,(ASCE)CO.1943-7862.0000100,Managerial Competencies of Female and Male Con...,Women; Discrimination; Workplace diversity; Pe...,Journal of Construction Engineering and Manage...,2009.0,United States,North America,https://scholar.google.com/scholar?hl=en&as_sd...,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(ASCE)CO.1943-7862.0000100,"[Female project managers, Managerial competenc..."
4,6,1-s2.0-S026378639800060X-main,Construction delay: a quantitative analysis,Construction management; Project planning; Con...,International Journal of Project Management,2000.0,Jordan,Asia,https://scholar.google.com/scholar?hl=en&as_sd...,936,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1-s2.0-S026378639800060X-main,"[Construction delay, Construction management, ..."

In [47]:
topics_dict['Logistics and Supply Chain Management']

['Construction logistics',
 'On',
 'Off',
 'Consolidation',
 'Construction supply chain',
 'Logistic']

If topics in the dataframe is in the value topics list of the dictionary, replace that topics in dataframe with summarized topics.

1. Create a Reverse Mapping Dictionary:
Convert topics_dict such that each original topic maps back to its summarized topic.

2. Process Each Row in the DataFrame:
For each topic in the 'topics' column of the DataFrame, check if it's in the reverse mapping dictionary. If it is, replace it with the summarized topic from the dictionary.

3. Remove Duplicates:
After processing, remove duplicate summarized topics from each list in the 'topics' column of the DataFrame.

Example dataframe input:
df = pd.DataFrame({
    'Index': [0, 1],
    'topics': [[Automated materials management, Inventory control, Construction logistics, Purchasing], [Materials management, Consolidation, Logistic, Green team risks]]
})

Example dictionary input:
topics_dict = {'Materials Management': ['Automated materials management', 'Materials management', 'Inventory control', 'Purchasing'], 'Logistics and Supply Chain Management':['Construction logistics',  'On-site logistics',  'Off-site logistics', 'Consolidation', 'Construction supply chain', 'Logistic']}

Example dataframe output:
pd.DataFrame({
    'Index': [0, 1],
    'topics': [[Materials Management, Logistics and Supply Chain Management], [Materials management, Logistics and Supply Chain Management, Green team risks]]
})

In [57]:
# Create a reverse mapping dictionary
reverse_mapping = {}
for summarized, topics in topics_dict.items():
    for topic in topics:
        reverse_mapping[topic] = summarized

# Replace topics in dataframe with summarized topics
def replace_with_summarized(topics_in_one_paper):
    return list(set([reverse_mapping.get(topic, topic) for topic in topics_in_one_paper]))

df['topics_summazried'] = df['topics'].apply(replace_with_summarized)

df.head()

,Index,File_Name,Paper_Name,Keywords,Journal_Name,Published_Year,Country,Continent,URL,Given Total,...,1985,1984,1983,1982,1981,1980,file_name,topics,topics_summazried,year_group
0,0,(ASCE)0733-9364(1986)112_3(346),RESOURCE MANAGEMENT IN CONSTRUCTION,-1,Journal of construction engineering and manage...,1986.0,United States,North America,https://scholar.google.com/scholar?hl=en&as_sd...,89,...,NaN,NaN,NaN,NaN,NaN,NaN,(ASCE)0733-9364(1986)112_3(346),"[Resource management, Construction industry, R...","[Construction Industry, Construction Planning ...",NaN
1,2,(ASCE)0742-597X(2005)21_1(2),Competency-Based Model for Predicting Construc...,Human factors; Professional development; Proje...,Journal of Management in Engineering,2005.0,United Kingdom,Europe,https://scholar.google.com/scholar?hl=en&as_sd...,311,...,NaN,NaN,NaN,NaN,NaN,NaN,(ASCE)0742-597X(2005)21_1(2),"[Construction project management, Competency-b...","[Human Resource Management, Self-control, Stak...",2000-2010
2,3,(ASCE)0887-3801(2006)20_3(165),Multi-Agent Framework for General-Purpose Situ...,Models; Simulation; Construction management; A...,Journal of Computing in Civil Engineering,2006.0,United States,North America,https://scholar.google.com/scholar?hl=en&as_sd...,73,...,NaN,NaN,NaN,NaN,NaN,NaN,(ASCE)0887-3801(2006)20_3(165),"[Multi-agent framework, Situational simulation...","[Multi-agent framework, Logical agent, Plannin...",2000-2010
3,5,(ASCE)CO.1943-7862.0000100,Managerial Competencies of Female and Male Con...,Women; Discrimination; Workplace diversity; Pe...,Journal of Construction Engineering and Manage...,2009.0,United States,North America,https://scholar.google.com/scholar?hl=en&as_sd...,5,...,NaN,NaN,NaN,NaN,NaN,NaN,(ASCE)CO.1943-7862.0000100,"[Female project managers, Managerial competenc...","[Construction Industry, Human Resource Managem...",2000-2010
4,6,1-s2.0-S026378639800060X-main,Construction delay: a quantitative analysis,Construction management; Project planning; Con...,International Journal of Project Management,2000.0,Jordan,Asia,https://scholar.google.com/scholar?hl=en&as_sd...,936,...,NaN,NaN,NaN,NaN,NaN,NaN,1-s2.0-S026378639800060X-main,"[Construction delay, Construction management, ...","[Construction Industry, Construction Project D...",2000-2010

In [62]:
df['topics_summazried'][6]

['4D technology',
 'resource management',
 '4D dynamic management',
 'project management',
 'construction progress control',
 'data warehousing',
 '3D-CAD technology',
 'construction planning',
 'site organization',
 'site space utilization',
 'workspace logistics',
 'decision-making support']

In [63]:
reverse_mapping

{'Automated materials management': 'Materials Management',
 'Materials management': 'Materials Management',
 'Inventory control': 'Materials Management',
 'Purchasing': 'Materials Management',
 'Construction logistics': 'Logistics and Supply Chain Management',
 'On': 'Logistics and Supply Chain Management',
 'Off': 'Logistics and Supply Chain Management',
 'Consolidation': 'Logistics and Supply Chain Management',
 'Construction supply chain': 'Logistics and Supply Chain Management',
 'Logistic': 'Logistics and Supply Chain Management',
 'Risk identification': 'Construction Project Risk Management',
 'Management risks': 'Risk Management',
 'Technical risks': 'Risk Management',
 'Green team risks': 'Risk Management',
 'Green materials risks': 'Risk Management',
 'Regulatory and economic risks': 'Risk Management',
 'safety climate': 'Safety and Occupational Health',
 'safety leadership': 'Safety and Occupational Health',
 'accidents in construction industry': 'Safety and Occupational Health',
 'construction workers': 'Safety and Occupational Health',
 'self': 'Safety and Occupational Health',
 'safety audits': 'Safety and Occupational Health',
 'construction site safety': 'Safety and Occupational Health',
 'occupational health and safety': 'Safety and Occupational Health',
 'Housing refurbishment': 'Construction Cost and Productivity',
 'Cost reduction': 'Construction Cost and Productivity',
 'Construction characteristics': 'Construction Cost and Productivity',
 'Construction industry sustainability': 'Construction Cost and Productivity',
 'Construction project delays': 'Construction Project Delays and Cost Overruns',
 'Economic growth': 'Construction and Economic Factors',
 'Lean principles': 'Innovation in Construction',
 'Industrialized housing production': 'Innovation in Construction',
 'Construction project culture': 'Construction Planning and Control',
 'Cash flow analysis': 'Construction Cost and Productivity',
 'Labour performance': 'Construction Cost and Productivity',
 'Revenue risk': 'Construction Cost and Productivity',
 'Cost of quality': 'Construction Cost and Productivity',
 'Performance metrics': 'Construction Performance Measurement and Evaluation',
 'Performance': 'Construction Performance Measurement and Evaluation',
 'Maintenance': 'Construction Performance Measurement and Evaluation',
 'Building project': 'Construction Cost and Productivity',
 'Productivity growth': 'Construction Cost and Productivity',
 'productivity monitoring': 'Construction Cost and Productivity',
 'Strategic management': 'Organizational Management and Strategy',
 'Role formation': 'Organizational Management and Strategy',
 'Project file': 'Organizational Management and Strategy',
 'Strategic planning': 'Organizational Management and Strategy',
 'Construction firm performance': 'Construction Performance Measurement and Evaluation',
 'Benchmarking models': 'Organizational Management and Strategy',
 'Technological attributes': 'Organizational Management and Strategy',
 'Strategic thrusts': 'Organizational Management and Strategy',
 'Human management': 'Construction and Human Resource Management',
 'Maintenance management': 'Construction Performance Measurement and Evaluation',
 'Systems approach': 'Organizational Management and Strategy',
 'Construction management evaluation': 'Organizational Management and Strategy',
 'People aspects of KM': 'Organizational Management and Strategy',
 'Contractor performance': 'Organizational Management and Strategy',
 'Organizational effectiveness': 'Organizational Management and Strategy',
 'Attitude towards change': 'Organizational Management and Strategy',
 'Knowledge tools': 'Organizational Management and Strategy',
 'Value management': 'Organizational Management and Strategy',
 'Organizational justice': 'Construction Ethics and Governance',
 'Organizational commitment': 'Organizational Management and Strategy',
 'Knowledge transfer': 'Organizational Management and Strategy',
 'Corporate image': 'Organizational Management and Strategy',
 'Organizational culture': 'Organizational Management and Strategy',
 'Data Envelopment Analysis (DEA)': 'Construction Technology and Innovations',
 'Prefabricated construction': 'Construction Technology and Innovations',
 'BIM (building information modeling)': 'Construction Technology and Innovations',
 '3D printing': 'Construction Technology and Innovations',
 'Digital systems integration': 'Construction Technology and Innovations',
 'Structural safety analysis': 'Construction Technology and Innovations',
 'Design for security': 'Construction Technology and Innovations',
 'Energy conservation': 'Construction Technology and Innovations',
 '4D visualization': 'Construction Technology and Innovations',
 'Internet of Things (IoT)': 'Construction Technology and Innovations',
 'Digital infrastructure': 'Construction and Digital Technologies',
 'Construction simulation': 'Construction Technology and Innovations',
 'Lean production management': 'Construction Technology and Innovations',
 'Integrated construction simulation': 'Construction Technology and Innovations',
 'Data handover': 'Construction Technology and Innovations',
 'Building information models': 'Construction Technology and Innovations',
 'BIM education': 'Construction Technology and Innovations',
 'Integrated maintenance monitoring': 'Construction Technology and Innovations',
 'Safety compliance checking': 'Construction Technology and Innovations',
 'Work structuring': 'Construction Technology and Innovations',
 'Agile project management': 'Construction Project Management',
 'Research trend': 'Construction Technology and Innovations',
 'Industrialization level': 'Construction Technology and Innovations',
 'Economic interdependencies': 'Construction Technology and Innovations',
 'Construction engineering and management': 'Construction Technology and Innovations',
 'behavioural safety': 'Construction Technology and Innovations',
 'Building design process': 'Construction Technology and Innovations',
 'Design integration': 'Construction Technology and Innovations',
 'Delay analysis': 'Construction Planning and Control',
 'Delay categorization': 'Construction Contracts and Legal Issues',
 'Power': 'Construction Contracts and Legal Issues',
 'Power sharing': 'Construction Contracts and Legal Issues',
 'Expert power': 'Construction Contracts and Legal Issues',
 'Procurement method selection': 'Construction Contracts and Legal Issues',
 'Power disposition': 'Construction Contracts and Legal Issues',
 'Power gap': 'Construction Contracts and Legal Issues',
 'Law': 'Construction Contracts and Legal Issues',
 'Contractual dispute avoidance': 'Construction Disputes and Claims',
 'labor market': 'Construction Contracts and Legal Issues',
 'Commercial return': 'Construction Contracts and Legal Issues',
 'Alternative dispute resolution': 'Construction Contracts and Legal Issues',
 'Contract management': 'Construction Contract Management',
 'Opposition': 'Construction Contracts and Legal Issues',
 'Partnership': 'Construction Contracts and Legal Issues',
 'Construction delays': 'Construction Project Management',
 'Time and cost overruns': 'Construction Project Management',
 'Delayed decision': 'Construction Project Management',
 'Inaccurate time estimation': 'Construction Project Management',
 'Poor cost estimation': 'Construction Project Management',
 'Financial constraints': 'Construction Project Management',
 'Future work': 'Construction Project Management',
 'Concession period design': 'Construction Project Management',
 'Construction project examples': 'Construction Project Management',
 'Government regulations': 'Construction Project Management',
 "Project manager's ignorance and lack of knowledge": 'Construction Project Management',
 'Multi': 'Project Management',
 'Project alliancing': 'Construction Project Management',
 'Interface Management': 'Construction Project Management',
 'European housing construction': 'Construction Project Management',
 'Occupation safety and health': 'Construction Project Management',
 'Project': 'Construction Project Management',
 'Construction project conflicts': 'Construction Disputes and Claims',
 'Construction stage': 'Construction Project Management',
 'Work': 'Construction and Workplace Environment',
 'Construction project implementation': 'Construction Project Management',
 'Contracts': 'Construction Project Management',
 'Informal sector': 'Construction Project Management',
 'Construction site mapping': 'Construction Project Management',
 'Project management functions': 'Construction Project Management',
 'Project organization': 'Construction Project Management',
 'Industry prospect': 'Construction Economics and Finance',
 'Causality links': 'Construction Economics and Finance',
 'Economic development': 'Construction and Economic Factors',
 'Granger causality test': 'Construction Economics and Finance',
 'Macroeconomy': 'Construction and Economic Factors',
 'Economic role': 'Construction Economics and Finance',
 'Financial closing': 'Construction Economics and Finance',
 'Inflation rate': 'Construction and Economic Factors',
 'Investment risk': 'Construction and Economic Factors',
 'International construction markets': 'International Construction and Global Market',
 'Public': 'Construction and Legal Issues',
 'financial risks': 'Construction Economics and Finance',
 'Revenue dependent infrastructure projects': 'Construction Economics and Finance',
 'ExxonMobil Costs': 'Construction Economics and Finance',
 'Social practices': 'Construction and Social Issues',
 'Social performance': 'Construction and Culture',
 'Social sustainability': 'Construction and Culture',
 'Circular economy': 'Construction and Culture',
 'Occupational stress': 'Construction and Workplace Environment',
 'Cultural diversity': 'Construction and Culture',
 'Racism': 'Construction and Culture',
 'Gender disparities': 'Construction and Culture',
 'Ethnic minorities': 'Construction and Culture',
 'Vocational training': 'Construction Education and Training',
 'Quality assurance': 'Construction Quality Management and Assurance',
 'On the job training': 'Construction Education and Training',
 'Graduate study': 'Construction Education and Training',
 'Undergraduate students': 'Construction Education and Training',
 'Skilled occupations': 'Construction Education and Training',
 'Construction skills crisis': 'Construction Education and Training',
 'Labour market': 'Construction Education and Training',
 'Construction education programs': 'Education and Training in Construction Management',
 'Training and skill development': 'Construction Training and Skill Development',
 'Construction project planning and control': 'Construction Planning and Control',
 'Time': 'Simulation and Modeling',
 'Construction site layout planning': 'Construction Planning and Control',
 'Design variation': 'Construction Planning and Control',
 'Unrealistic schedules': 'Construction Planning and Control',
 'Government permits': 'Construction Planning and Control',
 'Poor site management': 'Construction Planning and Control',
 'Construction project overhead expenses': 'Construction Planning and Control',
 'Construction project goals': 'Construction Planning and Control',
 'Construction project files': 'Construction Planning and Control',
 'Project life cycle': 'Construction Planning and Control',
 'Construction site operations': 'Construction Planning and Control',
 'Workflow management': 'Construction Planning and Control',
 'Construction progress meetings': 'Construction Planning and Control',
 'Risk of falls': 'Construction Planning and Control',
 "Analysis of contractors' pricing behavior": 'Construction Planning and Control',
 'Specification': 'Construction Planning and Control',
 'job satisfaction': 'Construction Planning and Control',
 'Supply chain issues': 'Construction Planning and Control',
 'trade': 'Construction Planning and Control',
 'Sustainability assessment': 'Sustainable Construction',
 'Construction industry culture': 'Sustainable Construction',
 'Sustainable urban housing': 'Sustainable Construction',
 'Building sustainability': 'Sustainable Construction',
 'Green construction': 'Sustainable Construction',
 'Sustainable construction management': 'Sustainable Construction',
 'Sustainable design': 'Sustainable Construction',
 'Sustainable building': 'Sustainable Construction',
 'Life cycle assessment': 'Sustainable Construction',
 'Environmental impacts': 'Construction Safety Management',
 'Budgeted environmental impacts': 'Sustainable Construction',
 'Actual environmental impacts': 'Sustainable Construction',
 'Activity': 'Sustainable Construction',
 'Sustainable target value (STV) design': 'Sustainable Construction',
 'Dispute resolution': 'Construction Disputes and Claims',
 'Construction disputes': 'Construction Disputes and Claims',
 'Joint ventures': 'Construction Disputes and Claims',
 'Claims administration': 'Construction Disputes and Claims',
 'Covid': 'Construction Disputes and Claims',
 'Force majeure provision': 'Construction Disputes and Claims',
 'Contractual terms and conditions': 'Construction Disputes and Claims',
 'Safety risk interactions': 'Construction Site Safety and Health',
 "construction workers' health": 'Construction Site Safety and Health',
 'Occupational health': 'Construction Site Safety and Health',
 'COVID': 'Construction Site Safety and Health',
 'Pandemics': 'Construction Site Safety and Health',
 'safety regulations': 'Construction Site Safety and Health',
 'Construction site safety': 'Construction Site Safety and Health',
 'Building site': 'Construction Site Safety and Health',
 'Safety communication': 'Construction Site Safety and Health',
 'Health and safety': 'Construction Site Safety and Health',
 'International construction': 'International Construction and Global Market',
 'International comparability': 'International Construction and Global Market',
 'International business distribution': 'International Construction and Global Market',
 'Colonial link': 'International Construction and Global Market',
 'Global marketplace': 'International Construction and Global Market',
 'Global': 'International Construction and Global Market',
 'Global procurement': 'International Construction and Global Market',
 'Internationalization': 'International Construction and Global Market',
 'International construction joint ventures': 'International Construction and Global Market',
 'International revenue': 'International Construction and Global Market',
 'International competitiveness': 'International Construction and Global Market',
 'International business': 'International Construction and Global Market',
 'Multinational enterprise': 'International Construction and Global Market',
 'International construction projects': 'International Construction and Global Market',
 'International and local contractors': 'International Construction and Global Market',
 'Human resource planning': 'Human Resource Management',
 'Employee involvement': 'Construction and Human Resource Management',
 'Employee resourcing': 'Construction and Human Resource Management',
 'Construction workforce': 'Construction Labor and Workforce Management',
 'Recruitment': 'Human Resource Management',
 'Training programs': 'Construction and Human Resource Management',
 'Organizational barriers': 'Construction and Human Resource Management',
 'Employee training and development': 'Construction and Human Resource Management',
 'Human resource capability': 'Construction and Human Resource Management',
 'Human resource strategies': 'Construction and Human Resource Management',
 'skill of labor': 'Construction and Human Resource Management',
 'Qualifications': 'Construction and Human Resource Management',
 'Workforce composition': 'Construction and Human Resource Management',
 'Coping strategies': 'Construction and Human Resource Management',
 'Employee commitment': 'Construction and Human Resource Management',
 'Occupational strain': 'Construction and Human Resource Management',
 'Performance improvements': 'Construction Performance Measurement and Evaluation',
 'Efficiency improvement': 'Construction Performance Measurement and Evaluation',
 'Construction performance measurement': 'Construction Performance Measurement and Evaluation',
 'Project performance': 'Construction Risk Management and Project Performance',
 'Performance variables': 'Construction Performance Measurement and Evaluation',
 'Construction innovation': 'Innovation in Construction',
 'Behavior of clients': 'Innovation in Construction',
 'Technological change': 'Innovation in Construction',
 'Innovation competence': 'Innovation in Construction',
 'Technological factors': 'Innovation in Construction',
 'Building information modeling (BIM)': 'Construction Performance Measurement',
 'Innovative activity': 'Innovation in Construction',
 'Routine work': 'Innovation in Construction',
 'Innovation diffusion process': 'Innovation in Construction',
 'Technological innovation': 'Construction Innovation and Technology Adoption',
 'Innovative design': 'Innovation in Construction',
 'Innovativeness': 'Innovation in Construction',
 'Construction industry innovation': 'Innovation in Construction',
 'Enabling innovation': 'Innovation in Construction',
 'Measuring innovation': 'Innovation in Construction',
 'Innovation process': 'Construction Innovation and Technology Adoption',
 'Leading indicators': 'Innovation in Construction',
 'Lagging indicators': 'Innovation in Construction',
 'Owner influence': 'Innovation in Construction',
 'Innovation champion': 'Innovation in Construction',
 'Lessons learned/knowledge management': 'Innovation in Construction',
 'Upper management support': 'Innovation in Construction',
 'Research and development': 'Innovation in Construction',
 'Organizational climate': 'Innovation in Construction',
 'Organizational structure': 'Innovation in Construction',
 'Innovation potential': 'Innovation in Construction',
 'Innovation success': 'Innovation in Construction',
 'Service quality': 'Construction Quality Management and Assurance',
 'Customer loyalty': 'Construction Quality Management and Assurance',
 'Quality function deployment': 'Construction Quality Management and Assurance',
 'Quality management system': 'Construction Quality Management and Assurance',
 'Customer satisfaction': 'Construction Quality Management and Assurance',
 'Quality performance': 'Construction Quality Management and Assurance',
 'Quality of treatment': 'Construction Quality Management and Assurance',
 'Quality costs': 'Construction Quality Management and Assurance',
 'Customer orientation': 'Construction Quality Management and Assurance',
 'Quality': 'Construction Quality Management and Assurance',
 'Quality improvement': 'Construction Quality Management and Assurance',
 'Quality culture': 'Construction Quality Management and Assurance',
 'Workplace diversity': 'Human Resource Management',
 'Social identity': 'Construction and Social Issues',
 'Safety climate': 'Construction and Social Issues',
 'Socio': 'Construction and Social Issues',
 'Cultural difference measurement': 'Construction and Social Issues',
 'Cultural distance': 'Construction and Social Issues',
 'Risk management practices': 'Construction Project Risk Management',
 'Construction project risk management': 'Construction Project Risk Management',
 'Risk analysis': 'Construction Project Risk Management',
 'Risk management techniques': 'Construction Project Risk Management',
 'Risk reduction': 'Construction Project Risk Management',
 'Risk transfer': 'Construction Project Risk Management',
 'Risk retention': 'Construction Project Risk Management',
 'Risk elimination': 'Construction Project Risk Management',
 'Construction risks': 'Construction Waste Management',
 'Ethical practices': 'Construction Ethics and Governance',
 'Ethical decision': 'Construction Ethics and Governance',

In [73]:
# Total number of topics before summarizing
print(len(set(item for sublist in df['topics'] for item in sublist)))

# Total number of topics after summarizing
print(len(set(item for sublist in df['topics_summazried'] for item in sublist)))

3983
3667

# Attach summarized topics to df after Topics summarization using GPT4

In [12]:
import pandas as pd
import ast
import os
import pickle
import re

In [5]:
# Directory where the txt files are located
folder_path = '/Users/yunshunzhong/Library/Mobile Documents/3L68KQB4HG~com~readdle~CommonDocuments/Documents/PhD Project/Prompt Engineering'
with open(os.path.join(folder_path, 'merged_df.pkl'), 'rb') as f:
    df = pickle.load(f)
df.head()

,Index,File_Name,Paper_Name,Keywords,Journal_Name,Published_Year,Country,Continent,URL,Given Total,...,1987,1986,1985,1984,1983,1982,1981,1980,file_name,topics
0,0,(ASCE)0733-9364(1986)112_3(346),RESOURCE MANAGEMENT IN CONSTRUCTION,-1,Journal of construction engineering and manage...,1986.0,United States,North America,https://scholar.google.com/scholar?hl=en&as_sd...,89,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(ASCE)0733-9364(1986)112_3(346),"[Resource management, Construction industry, R..."
1,2,(ASCE)0742-597X(2005)21_1(2),Competency-Based Model for Predicting Construc...,Human factors; Professional development; Proje...,Journal of Management in Engineering,2005.0,United Kingdom,Europe,https://scholar.google.com/scholar?hl=en&as_sd...,311,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(ASCE)0742-597X(2005)21_1(2),"[Construction project management, Competency-b..."
2,3,(ASCE)0887-3801(2006)20_3(165),Multi-Agent Framework for General-Purpose Situ...,Models; Simulation; Construction management; A...,Journal of Computing in Civil Engineering,2006.0,United States,North America,https://scholar.google.com/scholar?hl=en&as_sd...,73,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(ASCE)0887-3801(2006)20_3(165),"[Multi-agent framework, Situational simulation..."
3,5,(ASCE)CO.1943-7862.0000100,Managerial Competencies of Female and Male Con...,Women; Discrimination; Workplace diversity; Pe...,Journal of Construction Engineering and Manage...,2009.0,United States,North America,https://scholar.google.com/scholar?hl=en&as_sd...,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(ASCE)CO.1943-7862.0000100,"[Female project managers, Managerial competenc..."
4,6,1-s2.0-S026378639800060X-main,Construction delay: a quantitative analysis,Construction management; Project planning; Con...,International Journal of Project Management,2000.0,Jordan,Asia,https://scholar.google.com/scholar?hl=en&as_sd...,936,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1-s2.0-S026378639800060X-main,"[Construction delay, Construction management, ..."

In [6]:
df.shape

(577, 57)

In [22]:
# Read the text file
with open(os.path.join(folder_path, 'summarized_topics.txt'), 'r', encoding='utf-8') as file:
    content = file.read()

# Extract the content within square brackets using regular expressions
topics_lists = re.findall(r'\[.*?\]', content)

# Convert the string representation to actual Python lists
topics_lists = [ast.literal_eval(topic) for topic in topics_lists]

len(topics_lists)

577

In [26]:
# Append to the DataFrame
df['topics_summazried'] = topics_lists
df.head()

,Index,File_Name,Paper_Name,Keywords,Journal_Name,Published_Year,Country,Continent,URL,Given Total,...,1986,1985,1984,1983,1982,1981,1980,file_name,topics,topics_summazried
0,0,(ASCE)0733-9364(1986)112_3(346),RESOURCE MANAGEMENT IN CONSTRUCTION,-1,Journal of construction engineering and manage...,1986.0,United States,North America,https://scholar.google.com/scholar?hl=en&as_sd...,89,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(ASCE)0733-9364(1986)112_3(346),"[Resource management, Construction industry, R...","[Human Resource Management, Construction indus..."
1,2,(ASCE)0742-597X(2005)21_1(2),Competency-Based Model for Predicting Construc...,Human factors; Professional development; Proje...,Journal of Management in Engineering,2005.0,United Kingdom,Europe,https://scholar.google.com/scholar?hl=en&as_sd...,311,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(ASCE)0742-597X(2005)21_1(2),"[Construction project management, Competency-b...","[Project Management, Human Resource Management]"
2,3,(ASCE)0887-3801(2006)20_3(165),Multi-Agent Framework for General-Purpose Situ...,Models; Simulation; Construction management; A...,Journal of Computing in Civil Engineering,2006.0,United States,North America,https://scholar.google.com/scholar?hl=en&as_sd...,73,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(ASCE)0887-3801(2006)20_3(165),"[Multi-agent framework, Situational simulation...","[Technology and Innovation, Education and Trai..."
3,5,(ASCE)CO.1943-7862.0000100,Managerial Competencies of Female and Male Con...,Women; Discrimination; Workplace diversity; Pe...,Journal of Construction Engineering and Manage...,2009.0,United States,North America,https://scholar.google.com/scholar?hl=en&as_sd...,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(ASCE)CO.1943-7862.0000100,"[Female project managers, Managerial competenc...","[Human Resource Management, Diversity and Work..."
4,6,1-s2.0-S026378639800060X-main,Construction delay: a quantitative analysis,Construction management; Project planning; Con...,International Journal of Project Management,2000.0,Jordan,Asia,https://scholar.google.com/scholar?hl=en&as_sd...,936,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1-s2.0-S026378639800060X-main,"[Construction delay, Construction management, ...","[Project Management, Legal and Contractual Asp..."

In [27]:
# Total number of topics before summarizing
print(len(set(item for sublist in df['topics'] for item in sublist)))

# Total number of topics after summarizing
print(len(set(item for sublist in df['topics_summarized'] for item in sublist)))

3983
188

In [28]:
# Save the merged pdf with summarized topics
df.to_pickle('/Users/yunshunzhong/Library/Mobile Documents/3L68KQB4HG~com~readdle~CommonDocuments/Documents/PhD Project/Prompt Engineering/merged_df_with_summarized_topics.pkl')

In [1]:
len(['Human Resource Management', 'Project Management', 'Cost Management', 'Planning and Scheduling', 'Health and Safety', 'Technology and Innovation', 'Risk and Uncertainty Management', 'Sustainability and Environment', 'Supply Chain and Procurement', 'Legal and Contractual Aspects', 'Quality Management', 'Education and Training', 'Information Systems and Technology Adoption', 'Diversity and Workplace Culture', 'Strategic Management and Organizational Studies', 'International and Comparative Studies', 'Performance Measurement and Analytics', 'Knowledge Management and Transfer', 'Lean Construction and Process Improvement', 'Stakeholder Management and Engagement', 'Asset Management and Facilities Maintenance', 'Market Analysis and Economic Impact', 'Artificial Intelligence', 'Machine Learning']
)

24