In [1]:
import os
import time
import openai
import pickle
import ast
import pandas as pd
import re
import random
from openai import OpenAI

In [2]:


client = OpenAI(
    api_key='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',  
)

model_gpt4 = 'gpt-4o-mini'
max_num_tokens_gpt4 = 128000

In [3]:
def BasicGeneration(userPrompt):
    completion = client.chat.completions.create(
        model = model_gpt4,
        messages=[
            {"role": "user", "content": userPrompt}
        ]
    )
    return completion.choices[0].message.content

def RoleGeneration(userPrompt):
    completion = client.chat.completions.create(
        model = model_gpt4,
        messages=[
            {"role": "system", "content": "You are a expert in asset and construction management domain."},
            {"role": "user", "content": userPrompt}
        ]
    )
    return completion.choices[0].message.content

In [4]:
# load merged df with citations and topics
folder_path = '../../tcm/topics_outputs/2after_lda'
df = pd.read_excel(os.path.join(folder_path, 'topics_citation_full_dataset_with_additional_gl.xlsx'))
df

,Index,File_Name,Paper_Name,Keywords,Topics,Journal_Name,Published_Year,Country,Continent,URL,...,1987,1986,1985,1984,1983,1982,1981,1980,ground_truth_topics,lda_topics
0,0,(ASCE)0733-9364(1986)112_3(346).pdf,RESOURCE MANAGEMENT IN CONSTRUCTION,[],"['Resource management', 'Construction industry...",Journal of construction engineering and manage...,1986,United States,North America,https://scholar.google.com/scholar?hl=en&as_sd...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"['Resource planning', 'cost control', 'constru...","['analysis', 'earliest', 'resources', 'activit..."
1,2,(ASCE)0742-597X(2005)21_1(2).pdf,Competency-Based Model for Predicting Construc...,['Human factors; Professional development; Pro...,"['Construction project management', 'Competenc...",Journal of Management in Engineering,2005,United Kingdom,Europe,https://scholar.google.com/scholar?hl=en&as_sd...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"['Competency-based performance prediction', 'c...","['role', 'competencies', 'analysis', 'key', 'd..."
2,3,(ASCE)0887-3801(2006)20_3(165).pdf,Multi-Agent Framework for General-Purpose Situ...,['Models; Simulation; Construction management;...,"['Multi-agent framework', 'Situational simulat...",Journal of Computing in Civil Engineering,2006,United States,North America,https://scholar.google.com/scholar?hl=en&as_sd...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"['Multi-agent systems', 'situational simulatio...","['cm', 'events', 'operators', 'activities', 't..."
3,4,(ASCE)1532-6748(2001)1_2(17).pdf,Construction Management Practices Are Slowly C...,[],"['Strategic planning', 'Construction managemen...",Leadership and Management in Engineering,2001,NaN,4,https://scholar.google.com/scholar?hl=en&as_sd...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,['Strategic management in construction industr...,"['500', 'strategic management', 'based', 'mana..."
4,5,(ASCE)CO.1943-7862.0000100.pdf,Managerial Competencies of Female and Male Con...,['Women; Discrimination; Workplace diversity; ...,"['Female project managers', 'Managerial compet...",Journal of Construction Engineering and Manage...,2009,United States,North America,https://scholar.google.com/scholar?hl=en&as_sd...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"['Gender representation in construction', 'Man...","['competencies', 'focus', 'industry', '2009', ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000,1013,1013.pdf,Japan's building industry: The new model,['Japan; building industry; change; model buil...,"['Japanese building industry', 'Big five contr...",Construction Management and Economics,1993,United Kingdom,Europe,https://www.tandfonline.com/doi/abs/10.1080/01...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001,1014,1014.pdf,Forecasting methodology of national demand for...,['Building economics; forecasting; label stati...,"['Construction labour forecasting', 'National ...",Construction Management and Economics,1993,United States,North America,https://www.tandfonline.com/doi/abs/10.1080/01...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1002,1015,1015.pdf,Estimating industry-level productivity trends ...,['Total factor productivity; productivity; Hon...,"['Total-factor productivity', 'Building indust...",Construction Management and Economics,1993,Hong Kong,Asia,https://www.tandfonline.com/doi/abs/10.1080/01...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1003,1016,1016.pdf,Masonry productivity forecasting model,NaN,"['Masonry labor productivity', 'Productivity f...",Journal of construction engineering and manage...,1993,United States,North America,https://ascelibrary.org/doi/abs/10.1061/(ASCE)...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1004,1017,1017.pdf,Integrated construction project document manag...,['CIC; conceptual modelling; integration; docu...,"['Integrated document management', 'Computer i...",Proceedings of EuropIA,1993,Findland,Europe,https://citeseerx.ist.psu.edu/document?repid=r...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# delete 'topics' column if it exists
if 'topics' in df.columns:
    del df['topics']

In [7]:
# 42 topics
broader_topics_categories_42 = ['Project Management', 'Project planning', 'Construction scheduling', 'Resource Management in Construction', 'Cost and Financial Management', 'Scheduling Techniques', 'Risk Management', 'Quality Management', 'Technological Integration', 'Sustainability and Environmental Management', 'Human Resource Management', 'Safety Management', 'Stakeholder Engagement and Communication', 'Innovation and Technology in Construction', 'Contract Management', 'Performance Measurement and Evaluation', 'Project Complexity and Uncertainty Management', 'Cultural and Ethical Considerations', 'Change Management', 'Lean Construction Principles', 'Training and Skill Development', 'Project Success Factors', 'Research Methodologies in Construction Management', 'Collaborative Practices in Construction', 'Employment and Labor Market Dynamics', 'Decision-Making Processes in Construction', 'Public-Private Partnerships', 'Geographic and Cultural Contexts', 'Construction Logistics and Operations', 'Contractor Management and Performance', 'Educational Strategies for Construction Management', 'Data Management and Information Systems', 'Construction Economics', 'Health and Safety in Construction Projects', 'Strategic Management in Construction', 'Knowledge Management and Learning', 'Waste and Recycling in Construction', 'Emerging Trends and Future Directions', 'Crisis and Change Resilience in Construction', 'Market and Consumer Behavior in Construction', 'Analysis and Evaluation in Construction Management', 'Project Governance and Compliance']


broader_topics_categories_44 = ['Project Management Practices', 'Human Resource Management in Construction', 'Technology and Innovation in Construction', 'Risk Management in Construction', 'Sustainability and Environmental Management', 'Cost Management and Financial Analysis', 'Construction Planning and Scheduling', 'Safety Management in Construction', 'Supply Chain and Logistics Management', 'Construction Methods and Techniques', 'Stakeholder and Client Management', 'Quality Management and Assurance', 'Legal and Regulatory Compliance', 'Organizational Structure and Culture in Construction Firms', 'Education and Training in Construction', 'Construction Information Systems and ICT', 'Performance Measurement and Evaluation', 'Leadership in Construction Organizations', 'Conflict and Dispute Resolution', 'Construction Policy and Governance', 'Construction Design and Architectural Planning', 'Materials Management and Sustainability', 'Infrastructure and Mega-Projects Management', 'Construction Finance and Investment', 'Contract Management and Procurement', 'Communication and Collaboration in Construction', 'Market Analysis and Competitiveness', 'Knowledge Management in Construction', 'Construction Safety Technologies', 'Lean Construction Practices', 'Demolition and Waste Management', 'Ethics and Professionalism in Construction', 'Gender and Diversity in Construction', 'Construction Economics and Industrial Organization', 'Building Information Modeling (BIM) and Digital Technologies', 'Construction Automation and Robotics', 'Construction Workforce and Labor Management', 'Construction Data Analytics and Predictive Modeling', 'Construction Simulation and Modeling', 'Construction Asset Management', 'Decision-Making Processes in Construction', 'Construction Standards and Certifications', 'Digital Twin and Virtual Reality Applications', 'Public-Private Partnerships in Construction']



# 160 topics
broader_topics_categories_160 = ['Construction project information system', 'Project planning', 'Construction scheduling', 'Project delivery efficiency', 'Construction management process reengineering', 'Construction and management', 'Project life cycle management', 'Process performance improvement', 'Resource planning', 'Resource allocation', 'Site space utilization', 'Supply chain management', 'Construction resources', 'Construction workforce', 'Capacity planning', 'Cost control', 'Construction cost estimation', 'Budgeted environmental impacts', 'Cost-effective project management', 'Pricing process', 'Economic implications', 'Project scheduling', 'Critical Path Method', 'Linear regression', '4D dynamic management', 'Program Evaluation and Review Technique (PERT)', 'Schedule management', 'Construction project risk assessment', 'Risk identification', 'Risk response techniques', 'Fuzzy logic ', 'Hierarchical risk breakdown structure', 'Quality control', 'Total quality management', 'Quality performance measurement', 'Quality assurance', 'Building Information Modeling (BIM)', 'Digital transformation', 'Construction simulation', 'Integrated construction management', 'Technology adoption and implementation', 'Machine learning ', 'Internet of Things (IoT)', 'Sustainable construction', 'Environmental management', 'Life cycle assessment', 'Green building', 'Waste management', 'Human resource management', 'Workforce management', 'Job satisfaction', 'Training and development', 'Recruitment and selection', 'Gender diversity in construction ', 'Occupational health and safety (OHS)', 'Construction safety management systems', 'Safety training', 'Safety regulations', 'Safety performance improvement', 'Stakeholder management', 'Conflict analysis', 'Communication processes', 'Relationship dynamics', 'Community involvement', 'Technological innovation', 'Innovation management', 'R&D in construction', 'Innovative practices', 'Digital technologies', 'Contract management', 'Dispute resolution', 'Contractual arrangements', 'Alleviating contractual risks', 'Performance metrics', 'Performance evaluation', 'Benchmarking', 'Key performance indicators (KPIs)', 'Construction project complexity', 'Uncertainty in construction projects', 'Complexity management', 'Decision-making under uncertainty', 'Workplace diversity', 'Ethics in construction', 'Ethical considerations in project management', 'Change order management', 'Change management strategies', 'Managing construction project change', 'Lean construction', 'Last Planner System', 'Waste minimization', 'Construction skills training', 'Continuing education in construction management', 'Vocational training', 'Project success criteria', 'Factors contributing to project success', 'Performance-related project outcomes', 'Quantitative research methods', 'Qualitative research methods', 'Action research in construction', 'Collaborative construction management', 'Team-based organization', 'Collaborative working', 'Labor productivity', 'Skilled labor shortage', 'Labor market trends', 'Decision-making support systems', 'Multi-criteria decision making', 'Evidence-based decision-making', 'Public-private partnership projects', 'Contractual mechanisms in PPP', 'Governance in PPP ', 'Regional characteristics in construction', 'International construction market dynamics', 'Cultural impacts on construction', 'On-site logistics', 'Equipment management', 'Resource allocation behavior', 'Contractor assessment', 'Contractor selection methods', 'Performance evaluation of contractors', 'Construction management education', 'Effective teaching methods', 'Industry-academia collaboration', 'Information management', 'Database systems ', 'Integrated information system', 'Economic role of construction', 'Market dynamics in construction', 'Infrastructure economics', 'Safety planning', 'Safety evaluations', 'Health monitoring', 'Strategic alliances', 'Strategic procurement management', 'Business strategy in construction', 'Knowledge transfer in construction', 'Learning organizations in construction', 'Competency development', 'Construction waste management', 'C&D recycling practices', 'Waste identification and minimization', 'Future developments in construction', 'Trends in construction technology', 'Strategies for innovation adoption', 'Crisis management', 'Change resilience strategies', 'Risk response frameworks', 'Client satisfaction metrics', 'Construction consumer behavior', 'Client-driven design changes', 'Analytical design planning', 'Qualitative and quantitative analyses', 'Evaluation models and frameworks', 'Governance structures in projects', 'Regulatory compliance in construction', 'Ethical governance in construction']

In [8]:
categorize_topics_prompt = f'''
        As an expert in construction management, your task is to categorize a list of academic topics extracted from construction management journal papers into predefined broader categories. Follow these instructions carefully:

    1. Analyze each topic and assign it to the most appropriate broader category from the provided list.
    2. Use ONLY the provided broader categories. Do not create new categories.
    3. Categorize ALL topics. Do not leave any topic uncategorized.
    4. Output ONLY a list of broader topics. Do not include the original topics or category names in your output.
    5. If a topic could fit into multiple broader topics, choose the most relevant one based on the context of construction management.
    Broader topics are stored in this list: {broader_topics_categories_44}

    Topics are stored in this list: {df['Topics'][1]}
    The form of input is ['topic1', 'topic2', ...]
    The output should only be a list such as ['broader topic1', 'broader topic2', ...] without ANYTHING else.
    Anything else such as "Here are the broader topics for the given academic topics:" should not appear in the output.
    '''
RoleGeneration(categorize_topics_prompt)

"['Project Management Practices', 'Human Resource Management in Construction', 'Human Resource Management in Construction', 'Performance Measurement and Evaluation', 'Education and Training in Construction', 'Human Resource Management in Construction', 'Leadership in Construction Organizations', 'Human Resource Management in Construction', 'Human Resource Management in Construction', 'Performance Measurement and Evaluation']"

In [9]:
from tqdm.notebook import tqdm
def replace_with_summarized(topics_in_one_paper):
    categorize_topics_prompt = f'''
        As an expert in construction management, your task is to categorize a list of academic topics extracted from construction management journal papers into predefined broader categories. Follow these instructions carefully:

    1. Analyze each topic and assign it to the most appropriate broader category from the provided list.
    2. Use ONLY the provided broader categories. Do not create new categories.
    3. Categorize ALL topics. Do not leave any topic uncategorized.
    4. Output ONLY a list of broader topics. Do not include the original topics or category names in your output.
    5. If a topic could fit into multiple broader topics, choose the most relevant one based on the context of construction management.
    Broader topics are stored in this list: {broader_topics_categories_44}

    Topics are stored in this list: {topics_in_one_paper}
    The form of input is ['topic1', 'topic2', ...]
    The output should only be a list such as ['broader topic1', 'broader topic2', ...] without ANYTHING else.
    Anything else such as "Here are the broader topics for the given academic topics:" should not appear in the output.
    '''
    try:
        response = RoleGeneration(categorize_topics_prompt)

        # Find the list-like pattern within the string
        list_string_match = re.search(r"\[.*?\]", response)

        if list_string_match:
            # Extract the matched pattern
            response = list_string_match.group(0)
            # Convert the string representation of the list to an actual list
            actual_list = ast.literal_eval(response)
            # Remove duplicates while preserving order
            unique_list = list(dict.fromkeys(actual_list))
            return unique_list
        else:
            print("The topics have problems:", topics_in_one_paper)
            response = None  # Set response to None to trigger the loop again

    except TypeError:
        print("TypeError encountered. Retrying RoleGeneration...")
        response = None  # Set response to None to trigger the loop again
        time.sleep(random.uniform(0, 1))

In [10]:
# Register tqdm with pandas to use progress_apply
tqdm.pandas(desc="Processing rows")

# Apply the replace_with_summarized function to each row of the dataframe and create a new column 'broad_topics'
df['broad_topics'] = df['Topics'].apply(replace_with_summarized)
df

,Index,File_Name,Paper_Name,Keywords,Topics,Journal_Name,Published_Year,Country,Continent,URL,...,1986,1985,1984,1983,1982,1981,1980,ground_truth_topics,lda_topics,broad_topics
0,0,(ASCE)0733-9364(1986)112_3(346).pdf,RESOURCE MANAGEMENT IN CONSTRUCTION,[],"['Resource management', 'Construction industry...",Journal of construction engineering and manage...,1986,United States,North America,https://scholar.google.com/scholar?hl=en&as_sd...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"['Resource planning', 'cost control', 'constru...","['analysis', 'earliest', 'resources', 'activit...","[Human Resource Management in Construction, Co..."
1,2,(ASCE)0742-597X(2005)21_1(2).pdf,Competency-Based Model for Predicting Construc...,['Human factors; Professional development; Pro...,"['Construction project management', 'Competenc...",Journal of Management in Engineering,2005,United Kingdom,Europe,https://scholar.google.com/scholar?hl=en&as_sd...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"['Competency-based performance prediction', 'c...","['role', 'competencies', 'analysis', 'key', 'd...","[Project Management Practices, Human Resource ..."
2,3,(ASCE)0887-3801(2006)20_3(165).pdf,Multi-Agent Framework for General-Purpose Situ...,['Models; Simulation; Construction management;...,"['Multi-agent framework', 'Situational simulat...",Journal of Computing in Civil Engineering,2006,United States,North America,https://scholar.google.com/scholar?hl=en&as_sd...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"['Multi-agent systems', 'situational simulatio...","['cm', 'events', 'operators', 'activities', 't...","[Technology and Innovation in Construction, Co..."
3,4,(ASCE)1532-6748(2001)1_2(17).pdf,Construction Management Practices Are Slowly C...,[],"['Strategic planning', 'Construction managemen...",Leadership and Management in Engineering,2001,NaN,4,https://scholar.google.com/scholar?hl=en&as_sd...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,['Strategic management in construction industr...,"['500', 'strategic management', 'based', 'mana...","[Construction Policy and Governance, Project M..."
4,5,(ASCE)CO.1943-7862.0000100.pdf,Managerial Competencies of Female and Male Con...,['Women; Discrimination; Workplace diversity; ...,"['Female project managers', 'Managerial compet...",Journal of Construction Engineering and Manage...,2009,United States,North America,https://scholar.google.com/scholar?hl=en&as_sd...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"['Gender representation in construction', 'Man...","['competencies', 'focus', 'industry', '2009', ...","[Human Resource Management in Construction, Ge..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000,1013,1013.pdf,Japan's building industry: The new model,['Japan; building industry; change; model buil...,"['Japanese building industry', 'Big five contr...",Construction Management and Economics,1993,United Kingdom,Europe,https://www.tandfonline.com/doi/abs/10.1080/01...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[Construction Economics and Industrial Organiz...
1001,1014,1014.pdf,Forecasting methodology of national demand for...,['Building economics; forecasting; label stati...,"['Construction labour forecasting', 'National ...",Construction Management and Economics,1993,United States,North America,https://www.tandfonline.com/doi/abs/10.1080/01...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[Human Resource Management in Construction, Ma..."
1002,1015,1015.pdf,Estimating industry-level productivity trends ...,['Total factor productivity; productivity; Hon...,"['Total-factor productivity', 'Building indust...",Construction Management and Economics,1993,Hong Kong,Asia,https://www.tandfonline.com/doi/abs/10.1080/01...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[Construction Economics and Industrial Organiz...
1003,1016,1016.pdf,Masonry productivity forecasting model,NaN,"['Masonry labor productivity', 'Productivity f...",Journal of construction engineering and manage...,1993,United States,North America,https://ascelibrary.org/doi/abs/10.1061/(ASCE)...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[Construction Planning and Scheduling, Perform..."
1004,1017,1017.pdf,Integrated construction project document manag...,['CIC; conceptual modelling; integration; docu...,"['Integrated document management', 'Computer i...",Proceedings of EuropIA,1993,Findland,Europe,https://citeseerx.ist.psu.edu/document?repid=r...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[Construction Information Systems and ICT, Tec..."

In [11]:
type(df['broad_topics'][0])

list

In [30]:
# filter out rows with na values in df['Topics']
df = df[df['Topics'].notna()]
df

,Index,File_Name,Paper_Name,Keywords,Topics,Journal_Name,Published_Year,Country,Continent,URL,...,1986,1985,1984,1983,1982,1981,1980,ground_truth_topics,lda_topics,broad_topics
0,0,(ASCE)0733-9364(1986)112_3(346).pdf,RESOURCE MANAGEMENT IN CONSTRUCTION,[],"['Resource management', 'Construction industry...",Journal of construction engineering and manage...,1986,United States,North America,https://scholar.google.com/scholar?hl=en&as_sd...,...,0,0,0,0,0,0,0,"['Resource planning', 'cost control', 'constru...","['analysis', 'earliest', 'resources', 'activit...","[Resource Management in Construction, Construc..."
1,2,(ASCE)0742-597X(2005)21_1(2).pdf,Competency-Based Model for Predicting Construc...,['Human factors; Professional development; Pro...,"['Construction project management', 'Competenc...",Journal of Management in Engineering,2005,United Kingdom,Europe,https://scholar.google.com/scholar?hl=en&as_sd...,...,0,0,0,0,0,0,0,"['Competency-based performance prediction', 'c...","['role', 'competencies', 'analysis', 'key', 'd...","[Project Management Practices, Human Resource ..."
2,3,(ASCE)0887-3801(2006)20_3(165).pdf,Multi-Agent Framework for General-Purpose Situ...,['Models; Simulation; Construction management;...,"['Multi-agent framework', 'Situational simulat...",Journal of Computing in Civil Engineering,2006,United States,North America,https://scholar.google.com/scholar?hl=en&as_sd...,...,0,0,0,0,0,0,0,"['Multi-agent systems', 'situational simulatio...","['cm', 'events', 'operators', 'activities', 't...","[Education and Training, Project Management Pr..."
3,4,(ASCE)1532-6748(2001)1_2(17).pdf,Construction Management Practices Are Slowly C...,[],"['Strategic planning', 'Construction managemen...",Leadership and Management in Engineering,2001,NaN,4,https://scholar.google.com/scholar?hl=en&as_sd...,...,0,0,0,0,0,0,0,['Strategic management in construction industr...,"['500', 'strategic management', 'based', 'mana...","[Strategic Management in Construction, Constru..."
4,5,(ASCE)CO.1943-7862.0000100.pdf,Managerial Competencies of Female and Male Con...,['Women; Discrimination; Workplace diversity; ...,"['Female project managers', 'Managerial compet...",Journal of Construction Engineering and Manage...,2009,United States,North America,https://scholar.google.com/scholar?hl=en&as_sd...,...,0,0,0,0,0,0,0,"['Gender representation in construction', 'Man...","['competencies', 'focus', 'industry', '2009', ...","[Human Resource Management, Construction Econo..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
647,743,Texto.11.ConstructionQuality.pdf,Construction Quality Management: Principles an...,"['Manufacturing', 'Marketing', 'R&D and Engine...","['Quality management', 'Construction organisat...",NaN,2012,NaN,743,https://scholar.google.com/scholar?hl=en&as_sd...,...,0,0,0,0,0,0,0,"['Quality Management', 'Total Quality Manageme...","['learning', 'implementation', 'business', 'ac...","[Quality Control and Assurance, Organizational..."
648,744,Understanding the early stages of the innovati...,Understanding the early stages of the innovati...,"['Communication', 'critical perspective', 'dif...","['awareness', 'influence', 'communication netw...",Construction Management and Economics,2011,United Kingdom,Europe,https://scholar.google.com/scholar?hl=en&as_sd...,...,0,0,0,0,0,0,0,"['Innovation diffusion', 'awareness', 'influen...","['network', 'perspective', 'research', 'constr...",[Communication and Collaboration in Constructi...
649,745,Use of attitude congruence to identify safety ...,Use of attitude congruence to identify safety ...,"['Safety', 'small business.']","['Attitude congruence', 'Safety interventions'...",Construction Management and Economics,2011,United States,North America,https://scholar.google.com/scholar?hl=en&as_sd...,...,0,0,0,0,0,0,0,"['Construction industry safety', 'Occupational...","['attitudes', 'safety attitude', 'intervention...","[Organizational Behavior and Culture, Construc..."
650,746,Valuation of the minimum revenue guarantee and...,Valuation of the minimum revenue guarantee and...,"['BOT', 'infrastructure', 'real option', 'opti...","['Valuation', 'Minimum revenue guarantee', 'Op...",Construction Management and Economics,2006,China,Asia,https://scholar.google.com/scholar?hl=en&as_sd...,...,0,0,0,0,0,0,0,"['Build-Operate-Transfer', 'minimum revenue gu...","['concessionaire', 'options', 'value', 'mrg', ...","[Construction Finance and Investment, Infrastr..."
651,747,Work family enrichment in the Australian const...,Work-family enrichment in the Australian const...,"['Work-family enrichment', 'supervisor support...","['Work-family enrichment', 'Job design', 'Cons...",Construction Management and Economics,2010,Australia,Oceania,https://scholar.google.com/scholar?hl=en&as_sd...,...,0,0,0,0,0,0,0,"['Work–family enrichment', 'Australian constru...","['family', 'role', 'support', 'related resourc...","[Human Resource Management, Construction Polic..."

In [13]:
# save the dataframe back to xlsx file
save_path = '../../tcm/topics_outputs/3after_missing_topics_broad_topics'
df.to_excel(os.path.join(save_path, 'topics_citation_full_dataset_with_additional_glmb.xlsx'), index=False)